### ISSUE TITLE
finish_reason support in streams

### ISSUE THREAD

**Issue by IroncladAlibiMaker** [RageAgainstThePixel/OpenAI-DotNet#105]
As I can see, only stop finish reason is supported now in chat and completion streams.
Can you add length and content_filter finish reasons please?
Thnx.

**Comment by StephenHodgson** [comment]
Will do!

I think I'll actually change this to that if the finish reason is not null or empty to go ahead and raise it.

**Comment by IroncladAlibiMaker** [comment]
> Will do!
> 
> I think I'll actually change this to that if the finish reason is not null or empty to go ahead and raise it.

I'm sorry, can you explain further? I didn't understand what you mean by "go ahead and raise it."
Thank you.

**Comment by StephenHodgson** [comment]
For the older "regular" completions I'm not doing any final parsing and sending of whole completion result, like I do with streaming chat completions. (Mainly bc I didn't want to introduce a breaking change to how it works).

For the newer chat completion I am stitching together the results as they come in and I raise an additional event with the completed choice results, that includes all the information about that message. So I can add it there (see PR #106)

But in either case you can already get the finish reason, you just need to check for it in each event raised when streaming is taking place. See #106 for details)

**Comment by IroncladAlibiMaker** [comment]
I have this code.

```
foreach (var choice in result.Choices.Where(choice => choice.Message?.Content != null))
{
    if (!string.IsNullOrEmpty(choice.FinishReason))
    {
        //stop: API returned complete model output
        //length: Incomplete model output due to max_tokens parameter or token limit
        //content_filter: Omitted content due to a flag from our content filters
        //null: API response still in progress or incomplete

        if (choice.FinishReason == "length")
        {
            _finishReasonLength = true;
        }
        if (choice.FinishReason == "content_filter")
        {
            _finishReasonContentFilter = true;
            if (_finishReasonContentFilter)
            {
                logger.LogWarning("Content filter finish reason. " + choice.Dump());
            }
        }
    }
}

```
The FinishReason will always be 'stop', even though the returned context from OpenAI is truncated, meaning that the maximum token limit for output has been exceeded.

Is this considered correct behavior?
Thank you.

**Comment by StephenHodgson** [comment]
Sounds like it's a bug with the API.

This library only parses what is returned by the API itself.

One test you can do is to just debug and log every event, and make sure that the finish reason is not null or whitespace.
