### ISSUE TITLE
Having problems with any model other than Davinci.

### ISSUE THREAD

**Issue by Adeian** [RageAgainstThePixel/OpenAI-DotNet#109]
# Bug Report

## Overview
When using any model other than Davinci, the call to a chat completion fails with the error xxx Model is not supported.

## To Reproduce
OpenAI.Completions.CompletionResult result = await api.CompletionsEndpoint.CreateCompletionAsync(request, temperature: 0, model: Model.GPT3_5_Turbo, maxTokens: 200);
returns gpt-3.5-turbo is not supported (Parameter 'model')

## Expected behavior
OpenAI.Completions.CompletionResult result = await api.CompletionsEndpoint.CreateCompletionAsync(request, temperature: 0, model: Model.Davinci, maxTokens: 200);

Returns the expected response.

## Additional context
I have access to all of the current models with the exception of GPT-4 32K

**Comment by StephenHodgson** [comment]
You're using the wrong models for the end point.

https://platform.openai.com/docs/models/model-endpoint-compatibility
