### ISSUE TITLE
Add option to not validate API keys

### ISSUE THREAD

**Issue by YuraSuper2048** [RageAgainstThePixel/OpenAI-DotNet#114]
# Feature Request

## Problem
Some proxies that give access to OpenAI API do not have their keys start with sk- or sess-, and some users may want to use them.

## Solution
Add option to disable validation of API keys in constructor/client settings.

## Workaround
1. Clone the repository
2. Go to `./OpenAI-DotNet/OpenAIClient.cs`, find method `SetupClient`
3. Remove line `throw new InvalidCredentialException($"{OpenAIAuthentication.ApiKey} must start with '{AuthInfo.SecretKeyPrefix}'");`
4. Build the repository and add reference to your newly built library

**Comment by StephenHodgson** [comment]
I don't support other proxies other than the one in this project.
