### ISSUE TITLE
Add function calling to chat models

### ISSUE THREAD

**Issue by ADefWebserver** [RageAgainstThePixel/OpenAI-DotNet#115]
# Feature Request

## Is your feature request related to a problem? Please describe.
Implement support for the [just announced functions](https://openai.com/blog/function-calling-and-other-api-updates).

## Additional context
As discussed on the Discord channel, please assign this to me

**Comment by andreboom** [comment]
Any help needed, I will be glad to assist.

**Comment by ADefWebserver** [comment]
@andreboom Thanks. I hope to have it working by this weekend. I will reach out if I have any issues.

**Comment by ADefWebserver** [comment]
To implement the [updated API](https://platform.openai.com/docs/api-reference/chat/create). 

I need to:

- [ ] Add **function_call** to [Messages.cs](https://github.com/ADefWebserver/OpenAI-DotNet/blob/main/OpenAI-DotNet/Chat/Message.cs)
- [ ] Add **functions** to [ChatRequest.cs](https://github.com/ADefWebserver/OpenAI-DotNet/blob/main/OpenAI-DotNet/Chat/ChatRequest.cs)
- [ ] Add a unit test
- [ ] Test with gpt-3.5-turbo-0613

**Comment by ADefWebserver** [comment]
@StephenHodgson Are you still working on this, seems you also need to add **function_call** to [Messages.cs](https://github.com/ADefWebserver/OpenAI-DotNet/blob/main/OpenAI-DotNet/Chat/Message.cs) and to add **functions** to [ChatRequest.cs](https://github.com/ADefWebserver/OpenAI-DotNet/blob/main/OpenAI-DotNet/Chat/ChatRequest.cs)?

**Comment by StephenHodgson** [comment]
@ADefWebserver join us in the chat on Discord

**Comment by StephenHodgson** [comment]
https://github.com/openai/openai-cookbook/blob/main/examples/How_to_call_functions_with_chat_models.ipynb

**Comment by StephenHodgson** [comment]
https://platform.openai.com/docs/guides/gpt/function-calling

**Comment by phoben** [comment]
Great, I just need this. Looking forward!

**Comment by StephenHodgson** [comment]
Alright everyone, take one final look before the release tomorrow.
