### ISSUE TITLE
Issue with CreateCompletionAsync hanging on specific routes

### ISSUE THREAD

**Issue by PabloSergi** [RageAgainstThePixel/OpenAI-DotNet#119]
Hello,

I've encountered a perplexing issue with your library. Specifically, the CreateCompletionAsync method hangs indefinitely when routed to OpenAI API endpoints that have trace times of around 3-4 seconds.

Here is the problematic call I'm making:

```csharp
var result = await _client.CompletionsEndpoint.CreateCompletionAsync(
    prompt: $"Translate this to English:\n\n{text}",
    model: Model.Davinci,
    temperature: 0.3,
    maxTokens: 300,
    topP: 1.0,
    frequencyPenalty: 0.0,
    presencePenalty: 0.0
);
```
When the request is routed to API endpoints with trace times less than 3 seconds, it executes correctly. However, when the routing takes longer (about 3-4 seconds), the call hangs until a Microsoft-level timeout occurs.

Do you have any insights as to why this is happening? Could there be a conflict between the library's async mechanisms and the longer-than-usual response time of some routes? How might I fix this issue?

Thank you in advance for your help.

**Comment by StephenHodgson** [comment]
Are you using openAI or azure endpoints?

**Comment by StephenHodgson** [comment]
Do you have any exception logs that go along with this?

**Comment by PabloSergi** [comment]
> Are you using openAI or azure endpoints?

openAi

> Do you have any exception logs that go along with this?

No, unfortunately, I don't have any logs because after the code enters the CreateCompletionAsync function, it sometimes gets stuck indefinitely. I've tried setting a timeout of 200-300 seconds, and the only exception I receive is a timeout from Microsoft. I have a hypothesis that the issue might be related to the connection. I've performed traceroutes about 100 times, and around 90% of the requests take less than 1 second, but 10% of them take between 5-15 seconds (varies). It seems that all cases where the execution of the CreateCompletionAsync function gets stuck are related to these routes. I don't have any other explanations. I've been using this library on Google servers for the past 4 months, and it has been working perfectly fine there. Even now, it works perfectly fine on Google servers. But when I deployed the application to a different server today, this issue started occurring. I don't understand how to debug it because there are no error messages. Sometimes it just gets stuck in an infinite loop of requests and responses.

Im sure this willnt be usefull :)

Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

```
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
```

In those cases when the traceroute takes 5-15 seconds, the final destination is still reached. That's why no error is thrown. However, it seems that something happens along the way, causing the request to either hang somewhere or experience some traffic loss or some other issue that prevents the request from being terminated and instead leads to an infinite loop. Although the traceroute itself manages to reach the end. This is all speculation on my part, as I'm not a networking specialist, unfortunately.

**Comment by StephenHodgson** [comment]
Do you mind trying my unity version of this same package, and seeing if you can recreate the issue?

https://github.com/RageAgainstThePixel/com.openai.unity

**Comment by StephenHodgson** [comment]
I'm thinking might just be an issue with the server you're hosting it on.

But if you're able to give me a repro for a specific but with this library we can reopen another issue.

**Comment by PabloSergi** [comment]
> Do you mind trying my unity version of this same package, and seeing if you can recreate the issue?
> 
> https://github.com/RageAgainstThePixel/com.openai.unity

Today  hostings support answered me, that this problem in open Ai side. They are blocking traffic from poland/russia/kazakhstan. Right now im hosting of kazakhstan and looks like alot of users here have same issues. But anyway, this information looks very strange, cas OpenAI dont block 100% of requests. Anyway,  few ppl else approved this information for me.
