### ISSUE TITLE
Unable to use the OpenAI-DotNet client against the OpenAI-DotNet-Proxy for an Azure Open AI deployment

### ISSUE THREAD

**Issue by ryankanno** [RageAgainstThePixel/OpenAI-DotNet#122]
# Bug Report

## Overview

When using the Proxy set against an Azure Open AI instance, the example configuration for a client call against the proxy in the README doesn't appear to work when explicitly setting the domain. The construction assumes an api version endpoint of v1 (and has a check to prevent an empty v1, presumably for the openai endpoints). I went back to see if the version before that change would work (and explicitly set the api version to ""), but it's appending an extra / to the BaseRequest/BaseRequestUrlFormat, so the proxy is returning a 404.

Installed versions:
OpenAi-DotNet-Proxy==6.4.1
OpenAI-DotNet==6.4.1 and 7.0.1

## To Reproduce
1. Load up a proxy against an Azure Open AI instance
2. Write a small console program using the example (I just used the example client call with CreateCompletionAsync).
3. See 404

## Expected behavior
I expect the proxy to be able to forward a request generated by the client, but because of the way the client is modifying the BaseRequest/BaseRequestUrlFormat, I don't think the OpenAI-DotNet client can be used. I confirmed this by loading up Postman and issuing the request that should be forwarded, and the proxy did work.

**Comment by StephenHodgson** [comment]
I do not have access to OpenAI for Azure, so help here would be appreciated

**Comment by ryankanno** [comment]
Also, apologies for not being able to share code as it was done on another machine, but the examples I used to test were all from the README. There's a coupling between the available constructors and the underlying baserequest/formats being created (and the constructor that's used in the example assumes the OpenAI formats without a way to override the OpenAI for Azure domain).

**Comment by ryankanno** [comment]
@StephenHodgson If you can give some guidance on what you're thinking a good solve might be, I may be able to take a peek at it. Without knowing some of the original design decisions, there's many ways this can be solved (from changing settings from sealed to an interface or exposing construction that allows a caller to 'override' the internal formats - with the current constructors that are currently hiding these formats calling into it).

**Comment by StephenHodgson** [comment]
Yeah it's sealed for a reason

**Comment by StephenHodgson** [comment]
We should be able to update the classes to support both

**Comment by ryankanno** [comment]
Gotcha. So it sounds like we just need to modify this [construction](https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/098787cd8b414df3288b86f7cd93ecc51df348ee/OpenAI-DotNet/OpenAIClientSettings.cs#L75). Going to allow someone to pass in a domain here (since it could be the domain of the proxy), if this is set, going to use this as the marker to set baseformats, etc - will add in a check to make sure both aren't set.

**Comment by StephenHodgson** [comment]
yes likely we just need to be able to set a domain for the proxy

**Comment by ryankanno** [comment]
Had a few minutes to take a peek at this - so there is a slightly bigger issue that's happening because of the way the baseurlformat's are being internally assigned. 

Let's say you run the proxy with an embedded client to an Azure Open AI instance. Since that client's construction has an API version embedded, it needs to be removed from another caller using the new 'domain' parameter (otherwise, there will be two ?api-version's being appended, one from the caller and one from the embedded client). 

There's a few ways to handle this (some being more complex than others). What are your thoughts here @StephenHodgson? 

If the caller isn't passing in an api-version (because it's now embedded in the proxy, I think it's an easy solve (I just strip out the api-version if you pass in domain since that's indicative of using a proxy, but if the expectation is that the client of the proxy's api-version is to be respected - which I think makes more sense, then the proxy probably needs to merge that parameter and incorporate it into its calling pattern -> specifically, [here](https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/60e2b29fce737ac5050a3ee0a21f14cef4fbcb3e/OpenAI-DotNet-Proxy/Proxy/OpenAIProxyStartup.cs#L119)

**Comment by ryankanno** [comment]
Took a little longer look at this, I have a local fork where I have hacked this to work, but I do think the proxy needs to be modified. There's another issue with the OpenAI Azure endpoints (because some of the model/deployment ids are being embedded into the proxy client) - you can't make some of the calls wrt to what models are available because they're made into Azure Cognitive Services (to let's say get the [models you have available](https://learn.microsoft.com/en-us/rest/api/cognitiveservices/azureopenaipreview/models?source=recommendations), which may be out of scope for what this lib is trying to do, but I would think y'all might want to support that). To support this, I think what I describe below is probably what needs to happen.

The bigger issue with the proxy is that it probably should follow what a typical proxy does and if whatever auth you have implemented passes, it should just forward the request on without having baked in assumptions of what the caller wants to do. If that's the case, the only thing the proxy needs is an integration with the baseurl and the authentication (so that it can append the authentication into the underlying http client depending if it's azure/openai) and just take whatever is being fed in the original http request and forward it on. As it currently stands, it's leveraging the client, and this coupling has downstream effects, one being this issue here.

**Comment by StephenHodgson** [comment]
@ADefWebserver any input here?

**Comment by ADefWebserver** [comment]
@StephenHodgson - I sent you a message on discord to send me an email so I can give you an Azure OpenAI key so you can diagnose this. (I'm away from a computer a lot over the next two days so responses will be delayed)

**Comment by StephenHodgson** [comment]
After doing a bit more digging here.

@ryankanno were you setting the proper deployment and settings in your proxy client for azure?

You should move you azure client settings here, and then use your proxy settings in your client

**Comment by StephenHodgson** [comment]
Front end client settings:
```csharp
var authToken = await LoginAsync();
var auth = new OpenAIAuthentication($"sess-{authToken}");
var settings = new OpenAIClientSettings(domain: "api.your-custom-domain.com");
var api = new OpenAIClient(auth, settings);
```

Back end proxy client settings for azure:
```csharp
// get your access token using any of the MSAL methods
var accessToken = result.AccessToken;
var auth = new OpenAIAuthentication(accessToken);
var settings = new OpenAIClientSettings(resourceName: "your-resource", deploymentId: "deployment-id", apiVersion: "api-version", useActiveDirectoryAuthentication: true);
var api = new OpenAIClient(auth, settings);
```

**Comment by StephenHodgson** [comment]
I believe everything should work correctly except for image generation

**Comment by StephenHodgson** [comment]
I guess my last question is, do you even _need_ a proxy if you're using MSAL auth?

**Comment by ryankanno** [comment]
Apologies, I haven't looked at this for a bit. At the time, I wasn't using MSAL auth - In the scenario I was looking at, the proxy had the embedded credentials with the callers not needing to worry about it.

As for your question, I do think that a proxy is still useful in the scenario you're describing because one is able to centralize features (e.g. logging, etc) across all callers without having the callers needing to worry about it themselves.

**Comment by StephenHodgson** [comment]
So you did have the proxy client using the azure setup?

**Comment by StephenHodgson** [comment]
I was not able to repro with correct setup
