### ISSUE TITLE
ChatRequest forced function calls

### ISSUE THREAD

**Issue by Mitch528** [RageAgainstThePixel/OpenAI-DotNet#125]
# Bug Report

## Overview

Currently unable to manually call a function using the `function_call` parameter when using chat completion due to the API expecting either a string ("auto", "none") *or* a JSON object in the form of `{ "name": "function_name" }`.

The docs suggest it should be a JSON object through a string however doing so results in a bad request error. 

Exception:

```bash
System.Net.Http.HttpRequestException: StreamCompletionEnumerableAsync Failed! HTTP status code: BadRequest | Response body: {
  "error": {
    "message": "'$.function_call' is invalid. Please check the API reference: https://platform.openai.com/docs/api-reference.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

## To Reproduce
```cs
            var functions = new List<Function>
            {
                new Function(
                    nameof(WeatherService.GetCurrentWeather),
                    "Get the current weather in a given location",
                    new JsonObject
                    {
                        ["type"] = "object",
                        ["properties"] = new JsonObject
                        {
                            ["location"] = new JsonObject
                            {
                                ["type"] = "string",
                                ["description"] = "The city and state, e.g. San Francisco, CA"
                            },
                            ["unit"] = new JsonObject
                            {
                                ["type"] = "string",
                                ["enum"] = new JsonArray {"celsius", "fahrenheit"}
                            }
                        },
                        ["required"] = new JsonArray { "location", "unit" }
                    })
            };

            var chatRequest = new ChatRequest(messages, functions: functions, functionCall: "{ \"name\": \"GetCurrentWeather\" }", model: "gpt-3.5-turbo-0613");
```

## Expected behavior

Request to API not to fail.

**Comment by ADefWebserver** [comment]
I had the same problem and was not able to make it work.

**Comment by StephenHodgson** [comment]
I don't understand because the unit tests are passing.

Are you using the same example from my unit test?

**Comment by StephenHodgson** [comment]
What happens when you run your unit tests locally?

**Comment by Mitch528** [comment]
I modified the unit test to specify the function_call. The exisitng unit test uses "auto"

**Comment by ADefWebserver** [comment]
@Mitch528 - (side conversation) I ended up not needing this because I found that [ChatGPT wanted to make recursive calls](https://blazorhelpwebsite.com/ViewBlogPost/5067) and actually setting this to a specific function messed that up... I just forgot to make a bug report 😟

**Comment by Mitch528** [comment]
> @Mitch528 - (side conversation) I ended up not needing this because I found that [ChatGPT wanted to make recursive calls](https://blazorhelpwebsite.com/ViewBlogPost/5067) and actually setting this to a specific function messed that up... I just forgot to make a bug report 😟

Yep, I know. I'm currently doing the recursive calls too. However, there is a case where I want to call another function right after a different specific function is called automatically by ChatGPT.

**Comment by Josepi161** [comment]
Yeah I also have encountered this issue, failed so far in trying to find a work around.
If anyone comes up with a solution would love to hear.

**Comment by damiant3** [comment]
The problem stems from the fact that the ChatRequest.FunctionCall property is of type "string".  I have been able to get a message to go through and not be rejected by changing "string" to "object" and using a JsonObject like so:
var chatRequest = new ChatRequest( functionCall: new JsonObject
            {
                ["name"] = "FunctionName"
            },
            ...);

Using object will also allow you pass in a string like "auto" to ChatRequest.ctor.

However, I don't get the server to make args for this function for the same exact prompt when using "auto."

I remain frustrated by this.

**Comment by techjb** [comment]
Waiting to fix this issue.

**Comment by StephenHodgson** [comment]
I am sorry for the delay here. I want to focus on this soon, but want a better solution.

**Comment by StephenHodgson** [comment]
I updated the method to prevent a breaking change. You can assign "none", "auto", or "functionName" and it'll automatically assign JObject under the hood.
