### ISSUE TITLE
Update the streaming examples to use `string.IsNullOrEmpty` instead of `string.IsNullOrWhiteSpace`

### ISSUE THREAD

**Issue by Carl-Hugo** [RageAgainstThePixel/OpenAI-DotNet#129]
I suggest updating the streaming examples in the `README.md` file to use `string.IsNullOrEmpty` instead of `string.IsNullOrWhiteSpace`. 

What happens is `\n` is considered a whitespace, so when streaming the GPT markdown output, say there is a list, it is impossible to render the list correctly until receiving the final, complete message at the end, which defeats the purpose of steaming it in the first place. 

I scratched my head around this for a bit yesterday evening and dug way too deep into the code (including the BCL) to finally realize it was just the example I started with that introduced the issue. So my conclusion is: if I did hit this issue, others might as well, so why not make it better to save them some time?

I can open a PR if you want.

Thanks

**Comment by StephenHodgson** [comment]
I agree, I think I updated the unit tests but not the examples
