### ISSUE TITLE
Package support for .NETFramework, v4.7.*

### ISSUE THREAD

**Issue by fulldiver-drc** [RageAgainstThePixel/OpenAI-DotNet#136]
# Feature Request
Package support for .NETFramework v4.7.*

## Is your feature request related to a problem? Please describe.
I'm trying to install the OpenAI-DotNet Nuget package to a Visual Studio project, but am receiving a "package does not contain any assembly references that are compatible with that framework" error.
Due to some external constraints, the project target is limited to .NETFramework v4.7.*, so I am unable to modify the project to target net6.0, which the package description lists as the compatible target.

## Describe the solution you'd like
If at all feasible, I'd like support for .NETFramework v4.7.* to be added to the Nuget package.

## Describe alternatives you've considered
I've attempted targeting net6.0, but that causes significant breaking changes to dependencies elsewhere in the project, and the providers of those dependencies are not as accommodating as I'd have liked.
I previously attempted forking and modifying a different package to make it Framework v4.7.* compatible, but being completely clueless as to what I was doing, I was unfortunately unable to do so and as such have forgone attempting that for this OpenAI-DotNet package.

## Additional context
This seems to be by far the best and most comprehensive OpenAI library I can find. Other libraries that I have found to be compatible are missing certain functionalities or are otherwise not ideal for the project I am attempting. Assistance with getting this library to work with my project would be much appreciated.

**Comment by StephenHodgson** [comment]
Thank you so much for the complements on the library.

I'm sorry but I made a deliberate decision not to support framework 4.x.

This library uses the most modern features such as native System.Text.Json support, etc.

**Comment by fulldiver-drc** [comment]
Hi, I'm not opening the issue again, but I just wanted to say thanks. For both the library itself and for not giving me an easy fix for my issue. It gave me the motivation to try harder at modifying the library for compatibility, and I finally got it to work with my target framework. I definitely learned a lot from the effort, and your library was definitely worth it.
