### ISSUE TITLE
Update Fine Tuning endpoints

### ISSUE THREAD

**Issue by StephenHodgson** [RageAgainstThePixel/OpenAI-DotNet#137]
https://openai.com/blog/gpt-3-5-turbo-fine-tuning-and-api-updates

https://platform.openai.com/docs/api-reference/fine-tuning

**Comment by ADefWebserver** [comment]
I thought this was already working see: https://github.com/SyncfusionSuccinctlyE-Books/OpenAI-Succinctly/blob/main/Pages/FineTuningExample.razor

**Comment by paleicikas** [comment]
await service.FineTuningEndpoint.CreateFineTuneJobAsync(request);

<pre>
An unhandled exception occurred while processing the request.
HttpRequestException: CreateFineTuneJobAsync Failed! HTTP status code: BadRequest | Response body: {
"error": {
"message": "gpt-3.5-turbo-0613 can only be fine-tuned on the new fine-tuning API. This API is being deprecated. Please refer to our documentation: https://platform.openai.com/docs/api-reference/fine-tuning",
"type": "invalid_request_error",
"param": null,
"code": null
}
}
<pre>

**Comment by paleicikas** [comment]
wait or migrate to an other solution? quite small api change

**Comment by StephenHodgson** [comment]
> wait or migrate to an other solution? quite small api change

I was seeing that they had some issues with the new rollout of the api, so I was waiting a bit to see if they would make changes to stabilize it.

I did most of the work already, just need time to do a final review and merge it in. Just been busy with my current project, as we just entered QA before Alpha.

**Comment by Lenloo** [comment]
I'm also waiting

**Comment by fresche-gavin** [comment]
Also waiting :)

> I was seeing that they had some issues with the new rollout of the api, so I was waiting a bit to see if they would make changes to stabilize it.

It's been a month - I haven't seen further changes. Do you feel it has stabilized?

BTW, thanks @StephenHodgson for your work on this. This package seems to be the most active compare to others...

**Comment by StephenHodgson** [comment]
I'll put out a pre release next week

**Comment by fresche-gavin** [comment]
> I'll put out a pre release next week

Not trying to harass... well, I guess I am :)  Any update on this?

**Comment by StephenHodgson** [comment]
Yeah pretty much got everything done last week, just need to revert some of the breaking changes make it a little bit easier to use the old and the new.

**Comment by StephenHodgson** [comment]
If you're curious most of the work is in my unity project. I think I still need to port it over to this one, but it shouldn't take too long.
