### ISSUE TITLE
The name 'GetFileInfoAsync' does not exist in the current context

### ISSUE THREAD

**Issue by lbshopping** [RageAgainstThePixel/OpenAI-DotNet#139]
# Bug Report

## Overview

When trying to run this code:

```
var api = new OpenAIClient();
var fileData = await GetFileInfoAsync(fileId);
Console.WriteLine($"{fileData.Id} -> {fileData.Object}: {fileData.FileName} | {fileData.Size} bytes");
```

I get the following error:

**The name 'GetFileInfoAsync' does not exist in the current context**

The same happens for the following code:
```
var request = new CreateFineTuneRequest(fileData);
var fineTuneJob = await api.FineTuningEndpoint.CreateFineTuneJobAsync(request);
Console.WriteLine(fineTuneJob.Id);
```

**The type or namespace name 'CreateFineTuneRequest' could not be found (are you missing a using directive or an assembly reference?)**

## Additional context
net6.0-windows
OpenAI-DotNet Version 7.0.8

**Comment by StephenHodgson** [comment]
Sounds like you're missing the namespace imports required at the top of the file.

**Comment by StephenHodgson** [comment]
Check the unit test for implementation details

https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/2b1ba7c12a6130957d3394133f4dbc067c91a25b/OpenAI-DotNet-Tests/TestFixture_08_Files.cs#L28

**Comment by StephenHodgson** [comment]
Btw the current fine tunings endpoint was depreciated by openai, so there is no guarantee that the current endpoints are still working as intended. I do have a new task to address this updated endpoint implementation in #137

**Comment by lbshopping** [comment]
> Btw the current fine tunings endpoint was depreciated by openai, so there is no guarantee that the current endpoints are still working as intended. I do have a new task to address this updated endpoint implementation in #137

Yes, I noticed that. But for some reason I was unable to get it to work, I am using the following:

```
using OpenAI.Files;
using OpenAI;
using OpenAI.FineTuning;
using System.Text.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using System.Reflection.Metadata;

```

**Comment by StephenHodgson** [comment]
I just re-ran all my tests with my recent release, and I'm not able to reproduce this.

**Comment by lbshopping** [comment]
> I just re-ran all my tests with my recent release, and I'm not able to reproduce this.

Thanks! Are there any imports other than the above that I should import?

**Comment by lbshopping** [comment]
In the documentation it uses the following code:
```
var request = new CreateFineTuneRequest(fileData);
var fineTuneJob = await api.FineTuningEndpoint.CreateFineTuneJobAsync(request);
```

while in reality it should be:
```
var request = new CreateFineTuneJobRequest(fileData);
var fineTuneResponse = await OpenAIClient.FineTuningEndpoint.CreateFineTuneJobAsync(request);
```
So the documentation is outdated and that's why it was giving an error.

**Comment by StephenHodgson** [comment]
> So the documentation is outdated and that's why it was giving an error.

Ah I see. Thanks for the heads up. I'll be sure to update the docs along with #137
