### ISSUE TITLE
cannot use managed identity to authenticate to azure openAI. Is it only support key based authentication?

### ISSUE THREAD

**Issue by xinyeah** [RageAgainstThePixel/OpenAI-DotNet#145]
# Bug Report

**Comment by StephenHodgson** [comment]
Please fill out the issue details a little bit more so I can help you out.

How exactly are you implementing the managed Identity integration?

**Comment by xinyeah** [comment]
currently it supports Key based authentication to Azure OpenAI. I am wondering how can I leverage managed identity authentication to Azure OpenAI?

**Comment by StephenHodgson** [comment]
MSAL?

**Comment by StephenHodgson** [comment]
https://github.com/RageAgainstThePixel/OpenAI-DotNet#azure-active-directory-authentication
