### ISSUE TITLE
Using Azure OpenAI Service API Key

### ISSUE THREAD

**Issue by ezarebska** [RageAgainstThePixel/OpenAI-DotNet#148]
# Feature Request

I have an Azure OpenAI service created in the subscription and I wanted to use the API key to instantiate the client:
```csharp
client = new OpenAIClient(new OpenAIAuthentication(azureApiKey)); 

however, I am getting an error:

'DeserializeResponseAsync Failed! HTTP status code: Unauthorized | Response body: {
  "error": {
    "code": "invalid_api_key",
    "message": "Incorrect API key provided: sk-5dfb6***********************6dc8. You can find your API key at https://platform.openai.com/account/api-keys.",
    "param": null,
    "type": "invalid_request_error"
  }
}
```
Is there a chance to somehow use it?

Regards

**Comment by ADefWebserver** [comment]
You cannot use an OpenAI key. You have to use your **Azure** OpenAI key. 

![image](https://github.com/RageAgainstThePixel/OpenAI-DotNet/assets/1857799/0d9a7427-3c1e-4ffa-b7e5-f2b5c9663db6)

**Comment by StephenHodgson** [comment]
It sounds like you're not initializing the client correctly.
