### ISSUE TITLE
Images generated include a non-English language

### ISSUE THREAD

**Issue by Velocedge** [RageAgainstThePixel/OpenAI-DotNet#150]
# Bug Report

## Overview
I'm using api.ImagesEndPoint.GenerateImageAsync to create an image from a multiple choice question text.  The image contains a language I'm not familiar with but it's not English.  

## To Reproduce
1. Generate question text (ie. What type of metamorphosis do termites go through?)
2. Call api.ImagesEndPoint.GenerateImageAsync using the request: "If language is used, use English and create an image from this question: What type of metamorphosis do termites go through?"
3. Save the url to file and look

## Expected behavior
Expected any language to be in English since that's what everything else is.

## Screenshots
https://oaidalleapiprodscus.blob.core.windows.net/private/org-6JTh8tKCIlBzXKVs5em7ofTt/user-3IzkWnW4PdIgi1CNCsTMuhm9/img-ehJlZXn0KofKRbY6qM7QI24I.png?st=2023-10-23T09%3A00%3A20Z&se=2023-10-23T11%3A00%3A20Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-10-23T09%3A40%3A58Z&ske=2023-10-24T09%3A40%3A58Z&sks=b&skv=2021-08-06&sig=d2tOUG/wUXR/uO/Pa4Jc0oIjBrKhjVTlJ5h18vxmScI%3D

## Additional context
I've tried different words and just the question itself but it still comes out in "that" language.

![genImage_14450](https://github.com/RageAgainstThePixel/OpenAI-DotNet/assets/3296886/5b02a908-d914-4713-b19e-8d37f1cbc542)
![genImage_14452](https://github.com/RageAgainstThePixel/OpenAI-DotNet/assets/3296886/5f10a227-d111-45f9-a22b-99baec1692db)
![genImage_14449](https://github.com/RageAgainstThePixel/OpenAI-DotNet/assets/3296886/0691e13f-776e-4a0b-b7a3-e55fd532355b)

**Comment by StephenHodgson** [comment]
It's likely a problem with the model on OpenAI not with this library

**Comment by Velocedge** [comment]
That's what I was thinking but wasn't sure if you provided a way to specify language.  I didn't see any way to.  Everything else has been great... except this bit!  ;-)

**Comment by Velocedge** [comment]
Do you know if this uses DALL-E 2 or DALL-E 3?

**Comment by StephenHodgson** [comment]
DALL-E 3 has not been released yet for public
