### ISSUE TITLE
HttpClient.Timeout  of 100 seconds

### ISSUE THREAD

**Issue by abnite** [RageAgainstThePixel/OpenAI-DotNet#151]
I am New to this, I keep getting this error when running some prompts. can you pls assist how to resolve it?

**An unhandled exception occurred while processing the request.
SocketException: Operation canceled
Unknown location

IOException: Unable to read data from the transport connection: Operation canceled.
System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

TaskCanceledException: The operation was canceled.
System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, bool async, CancellationToken cancellationToken)

TimeoutException: The operation was canceled.
System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, bool async, CancellationToken cancellationToken)

TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.**

**Comment by StephenHodgson** [comment]
you should be able to configure the timeout with a custom http client you pass into the OpenAIClient constructor

https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/9efcacdb728d57c37d88022e05c9027b142a3e39/OpenAI-DotNet/OpenAIClient.cs#L38

**Comment by ADefWebserver** [comment]
This worked for mee to set timeout 520: 

`var api = new OpenAIClient(new OpenAIAuthentication(ApiKey, Organization),null,new HttpClient() { Timeout= TimeSpan.FromSeconds(520) });`

https://github.com/ADefWebserver/AIStoryBuilders/blob/636b30f2aab3d92b0086f494f4658d5bcb5fb3eb/Data/OrchestratorMethods.CreateNewChapters.cs
