### ISSUE TITLE
Support Dalle with OpenAI for Azure 

### ISSUE THREAD

**Issue by subbu5280wipro** [RageAgainstThePixel/OpenAI-DotNet#152]
I tried with endpoint with appkey . 
another way using msal accesstoken also i tried.

**://xxx.openai.azure.com/openai/images/generations:submit?api-version=2023-06-01-preview**_/v1/images/generations_
Here bold one is my endpoint(://xxx.openai.azure.com/openai/images/generations:submit?api-version=2023-06-01-preview), its automatically adding italic(/v1/images/generations). because of that i am not able to access dalle.

Can you make any tutorial for that.

**Comment by StephenHodgson** [comment]
https://feedback.azure.com/d365community/idea/f2204961-d97f-ee11-a81c-6045bdb7ea56
