### ISSUE TITLE
Support for new OpenAI APIs announced at DevDay

### ISSUE THREAD

**Issue by Mitch528** [RageAgainstThePixel/OpenAI-DotNet#154]
New & Updated APIs:

* Assistants
* GPT-4 with vision
* [x] DALLE-3
* [x] TTS

**Comment by StephenHodgson** [comment]
Already on it

**Comment by tghamm** [comment]
@StephenHodgson will the 7.1 milestone (that I see you're furiously working on, thank you!!) include support for [JSON Mode](https://platform.openai.com/docs/guides/text-generation/json-mode) and [Reproducible Outputs](https://platform.openai.com/docs/guides/text-generation/reproducible-outputs)?  Thanks for all your hard work!

**Comment by ADefWebserver** [comment]
I need [JSON Mode](https://platform.openai.com/docs/guides/text-generation/json-mode) like yesterday 😜 So happy you are working on this so fast!

**Comment by StephenHodgson** [comment]
@tghamm @ADefWebserver gonna get just a few things out today for 7.1, but will def try to knock out the rest in 7.2

**Comment by StephenHodgson** [comment]
I'd like to close this and split it out into more targeted issues tbh to track better

**Comment by ADefWebserver** [comment]
> @tghamm @ADefWebserver gonna get just a few things out today for 7.1, but will def try to knock out the rest in 7.2

Understood, it is-a-lot of stuff!
