### ISSUE TITLE
Change GenerateImageAsync return objects => include revised_prompt

### ISSUE THREAD

**Issue by LucGosso** [RageAgainstThePixel/OpenAI-DotNet#164]
# Feature Request

For Dalle3 they now return the revised_prompt, 

would be nice if GenerateImageAsync returned same object => https://platform.openai.com/docs/api-reference/images/object
```json
{
  "url": "...",
  "revised_prompt": "..."
}
```
instead of string array. 

Thank you!

**Comment by StephenHodgson** [comment]
Sure, but is a breaking change

**Comment by LucGosso** [comment]
Make an overload of GenerateImageAsync  ?

**Comment by StephenHodgson** [comment]
It's ok, I already have a plan for what to do. I also need to keep the unity package version of this in sync with proposed changes as well.
