### ISSUE TITLE
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Cannot implicitly convert type 'System.Text.Json.JsonElement' to 'string''

### ISSUE THREAD

**Issue by HashemGo** [RageAgainstThePixel/OpenAI-DotNet#172]
# Bug Report

## Overview
result.FirstChoice.Message.Content make this error after update

is there any way to fix this error 

## Screenshots
![image](https://github.com/RageAgainstThePixel/OpenAI-DotNet/assets/42634137/71a9b542-efaa-468e-abb2-b2f3b397a3ed)

**Comment by HashemGo** [comment]
to fix this Error
`Convert.ToString(result.FirstChoice.Message.Content)`

**Comment by StephenHodgson** [comment]
IDK what your `AIModel.ctr` signature is.

The message content is dynamic, and depending on if you are making a function call can change the return type of the message content from string to JsonElement.  I encourage you to use the explicit ToString method or explicitly state the type you expect.
