### ISSUE TITLE
Add support for specifying image `detail` in chat completion requests

### ISSUE THREAD

**Issue by rpendleton** [RageAgainstThePixel/OpenAI-DotNet#176]
# Feature Request

## Is your feature request related to a problem? Please describe.

The `gpt-4-visual-preview` model supports processing images using two different levels of detail: `high` or `low`. OpenAI-DotNet allows adding images to chat completion requests, but it doesn't allow specifying this optional parameter.

According to the [OpenAI documentation](https://platform.openai.com/docs/guides/vision/low-or-high-fidelity-image-understanding), this parameter defaults to `auto`, which picks the detail level automatically based on the image resolution. There are several reasons why being able to override this level of detail would be useful though.

For example:

* `low` detail requests will always use 85 tokens per image, whereas a `high` detail request could use up to 1,445 tokens per image in the worst case (768x2048 image, which takes 8 512x512 tiles). Using fewer tokens can reduce costs (and/or lead to more predictable costs), and it also allows conversations run longer before hitting the context limit.
* `low` detail requests can result in faster completion responses

## Describe the solution you'd like

When constructing `Content` with an image url, it would be nice if I could specify the level of `detail` to use.

## Describe alternatives you've considered

The only alternatives I could think of were to:
* somehow intercept the request to add the `detail` property before sending the request
* manually rescale every image to `512x512` to hopefully force a `low` detail request

Neither of these alternatives are very sustainable though.

**Comment by StephenHodgson** [comment]
None of their documentation shows where to add this parameter.
