### ISSUE TITLE
Chunk large moderation requests for more accuracy

### ISSUE THREAD

**Issue by kikaragyozov** [RageAgainstThePixel/OpenAI-DotNet#182]
# Feature Request

The Open API documentation guidelines state that for higher accuracy in moderation responses, texts larger than 2000 characters should, if possible, be split in chunks of less than 2000 characters, which would lead to better results returned from the moderation endpoint.

If possible, we should handle this for the end user. Additionally, we should consider if it won't be a bad idea to add a overlap of X characters to the split chunks, so "some" context between them is maintained.

  * Chunking is enabled only when a request would require more than 2 chunks to be processed.
  * Size for each chunk is 1000 characters.
  * Overlap for each chunk is 10%.
  * The moment a request is flagged, the method returns without proceeding with the other chunks.

**Comment by kikaragyozov** [comment]
If this is something worth integrating, I might attempt to tackle this. Although I'm not sure if we should give the consumer the ability to define how long the roll-over should be, if we do decide to also integrate such a feature.

**Comment by ADefWebserver** [comment]
As a person who uses this library a lot to create embeddings, I suggest that the library not implement features that go beyond what is required to interface with the OpenAI API. 

For example, 1000 character chunks with 10% overlap would never work for me. Therefore a lot of time and code would be spent trying to address my needs and others. Honestly an entire library could be designed to addresses overlap, token management, ect.

**Comment by StephenHodgson** [comment]
I also agree with @ADefWebserver.

I want this library to remain as bare ones as possible and only handle the API itself. Additional functionality should be taken up by consumers of this library.

It's part of why I never directly looked into adding langchain or agents (two features I heavily use on top of this library).

**Comment by ADefWebserver** [comment]
> It's part of why I never directly looked into adding langchain or agents

Yeah that would have been a lot of wasted effort based on what OpenAI just released...

**Comment by StephenHodgson** [comment]
We will see. Tbh not a fan of threads and assistants yet.

The API is convoluted.

**Comment by kikaragyozov** [comment]
> I also agree with @ADefWebserver.
> 
> I want this library to remain as bare ones as possible and only handle the API itself. Additional functionality should be taken up by consumers of this library.
> 
> It's part of why I never directly looked into adding langchain or agents (two features I heavily use on top of this library).

Isn't LangChain python-specific? How would you use it in a .NET managed world anyways?

I agree with your concerns. There's an argument to be made here what constitutes a functionality that is "unnecessary" and goes beyond the scope of the project in terms of bare-bones functionality, versus what is.

For example, the already existing `GetModerationAsync` method in `ModerationsEndpoint` is entirely unnecessary if we wanted a strict bare-bones implementation.

Similarly, if it were to be changed to do chunking as per general OpenAI documentation guidelines strictly adhering the given Moderations endpoint's intended usage, I don't see how that would be a "bloated" feature going beyond the bare-bones implementation world. If anything, it's an enhancement to an already existing method. It just works better.

> As a person who uses this library a lot to create embeddings, I suggest that the library not implement features that go beyond what is required to interface with the OpenAI API.
> 
> For example, 1000 character chunks with 10% overlap would never work for me. Therefore a lot of time and code would be spent trying to address my needs and others. Honestly an entire library could be designed to addresses overlap, token management, ect.

I'm not sure how embeddings play into the context of making a moderation request. Am I missing something?

**Comment by StephenHodgson** [comment]
> Isn't LangChain python-specific?

Sure the original implementation is. But Lang chain is more of a design pattern and process. I have a c sharp version based on this library that I use for clients.

**Comment by ADefWebserver** [comment]
> I'm not sure how embeddings play into the context of making a moderation request. Am I missing something?

It was just that this exact same issue came up in regards to getting embeddings.

**Comment by StephenHodgson** [comment]
I think the difference between the moderation call you mention, is that it's only returning a result based off of the input. 

Where is your recommendation would fundamentally change a call to the API

**Comment by kikaragyozov** [comment]
> I think the difference between the moderation call you mention, is that it's only returning a result based off of the input.
> 
> Where is your recommendation would fundamentally change a call to the API

My suggestion targets `GetModerationAsync` which returns a `bool`. Nothing would break, or change. It would be a direct "enhancement".

**Comment by StephenHodgson** [comment]
If you want to write up a pull request to so we can review the changes I think that would probably settle the discussion.
