### ISSUE TITLE
Operation Cancelled

### ISSUE THREAD

**Issue by gertbus** [RageAgainstThePixel/OpenAI-DotNet#185]
# Bug Report

## Overview
Sometimes i get an operation cancelled issue. Maybe it's on the openAI side of course, so if so let me know.

## To Reproduce
You can easily reproduce the problem with the following code :
```csharp
using System.Threading;

using OpenAI;
using OpenAI.Assistants;
using OpenAI.Threads;

var api = new OpenAIClient ( "your_API_key" );

var assistant = await api.AssistantsEndpoint.RetrieveAssistantAsync ( "your_Assistant_key" );
Console.WriteLine ( $"{assistant} -> {assistant.CreatedAt}" );

var question = Console.ReadLine ();
var messages = new List<Message> { new Message(question)};
var threadRequest = new CreateThreadRequest ( messages );
var run = await assistant.CreateThreadAndRunAsync ( threadRequest );
Console.WriteLine ( $"Created thread and run: {run.ThreadId} -> {run.Id} -> {run.CreatedAt}" );

//while( run.Status != RunStatus.Completed)
//{

//    Console.WriteLine ( $"Run status: {run.Status} -> {run.CreatedAt}" );
//    //Thread.Sleep ( 1000 );
//    run = await run.WaitForStatusChangeAsync ();
//}
run = await run.WaitForStatusChangeAsync ();
var thread = await api.ThreadsEndpoint.RetrieveThreadAsync ( run.ThreadId );

//Console.WriteLine ( $"Run status changed: {run.Status} -> {run.CreatedAt}" );

// Status is completed here, so U can list the messages

var messageList = await thread.ListMessagesAsync ();

foreach (var message in messageList.Items)
{
    Console.WriteLine ( $"{message.Id}: {message.Role}: {message.PrintContent ()}" );
 }
```
[](![Schermafbeelding 2023-11-27 114851](https://github.com/RageAgainstThePixel/OpenAI-DotNet/assets/128687307/7b400a1f-9882-4c6d-a304-2c85b9b35529))

**Comment by kikaragyozov** [comment]
Hello there!

How long before the cancellation occurs? There's a 10 minute expiration for runs over at OpenAI's side, though it's definitely weird that `WaitForStatusChangeAsync` throws an `OperationCanceledException/TaskCanceledException` when the consumer has not supplied a cancellationToken. We'd expect to see a `RunStatus.Expired` if something like that happens, right?

**Comment by kikaragyozov** [comment]
There's a default value for `timeout` parameter that is set to 30 seconds if no parameter is supplied. If you want to wait indefinitely, pass the value `-1` and that should solve your issue.

```
run = await run.WaitForStatusChangeAsync(timeout: -1);
```

**Comment by gertbus** [comment]
Very short time. It happens about 30 seconds after the call.

**Comment by kikaragyozov** [comment]
@StephenHodgson Maybe for when the next major iteration is bound to take place with Threads/Assistants, we should consider changing `int? timeout = null` to simply `int timeout = -1`? 

The default value of `null` is rather obscuring the default behavior which adds a 30 seconds timeout. Most people if they're coming from the async world, especially Semaphore which also supports timeouts, always default down to an infinite timeout, unless done [explicitly](https://github.com/dotnet/runtime/blob/721c445e494a1d85d2d12e7a99ac2cd94bb898fa/src/libraries/System.Private.CoreLib/src/System/Threading/SemaphoreSlim.cs#L493).

We should either aim for `int timeout = 30` or `int timeout = -1` to also conform with already existing async primitives.

**Comment by gertbus** [comment]
Awesome library guys! Thx again for the fast response !

**Comment by gertbus** [comment]
timeout = -1 will give u an error. timeout;=0 will do the trick.

**Comment by StephenHodgson** [comment]
The timeout is by design.

You can either add a try/catch or specify a specific amount to wait.

FYI some status changes are not always reliable (like in the case of cancellation, a run may never come back as cancelled)

> We should either aim for int timeout = 30 or int timeout = -1 to conform with already existing async primitives.

Sure we can add the default time instead of null. I also didn't want it to be infinite, because of the unreliable nature of status changes.
