### ISSUE TITLE
Response data is not properly being logged when unsuccessful.

### ISSUE THREAD

**Issue by Vitoc456** [RageAgainstThePixel/OpenAI-DotNet#19]
# Feature Request

## Is your feature request related to a problem? Please describe.
Please provide more information from Response when IsSuccessStatusCode = false

### Describe the solution you'd like

When CompletionRequest's Response.IsSuccessStatusCode = false much of the useful information being returned from the server is lost. For example, "BadRequest" status code doesn't explain **why** it was a bad request which the server's response often explains in more detail.

### Proposed solution:

Include the server's Response.Content in the message being bubbled up in the exception. Consider including the following in the message included in the HttpRequestException message:
`Content: {await response.Content.ReadAsStringAsync()}`

### More context:

Using OpenAI CompletionRequest was failing for me via BadRequest errors when my prompt was growing past about 384 characters in length. After tweaking the code to provide the Response.Content I found the server was telling me the total tokens (prompt+response) were going over the max. The response also included the solution to resolve the problem, but that critical information was not being bubbled up.

**Comment by StephenHodgson** [comment]
Please be sure to stick to the issue template. I felt like you were yelling at me with everything big and bold 😅

**Comment by Vitoc456** [comment]
Sorry! My first contribution to any open source project; learning as I go, thanks for your patience. I pushed a branch w/ proposed fix. I don't think I linked it properly to this issue or do I do that in the PR?

**Comment by StephenHodgson** [comment]
That's great!  

I do have an idea of what I want to do here but I would love to see your pull request first. 

If you forked the repository you should be able to make a pull request

**Comment by Vitoc456** [comment]
Ah, that makes sense now. Forked & changes pushed, PR created. Let me know if I'm doing anything else wrong or not following proper etiquette. :)

**Comment by StephenHodgson** [comment]
You did it right! Thanks so much for suggesting these changes. I agree, and I'll follow up and make these changes by the end of the weekend.
