### ISSUE TITLE
Dedicated exceptions for specific events

### ISSUE THREAD

**Issue by kikaragyozov** [RageAgainstThePixel/OpenAI-DotNet#193]
I see there's some code that's been added that populates the headers for rate limiting, but they're unusable as our current implementations require a successful status code response before we set the response data. If the response is not a success status code (200-299) we throw an exception.

Currently the `BaseResponse` looks the [following way](https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/929f45e7aaad0e0ad8e16e6c2b6a273430a93be9/OpenAI-DotNet/Common/BaseResponse.cs#L6).

I suggest if we do decide to tackle this, to create a custom `OpenAIClientRateLimitException` that end-users can inspect and access all those related headers, which should also end up cleaning the `BaseResponse` a bit. The cleaning part though would introduce breaking changes if we do decide to follow through with it.

Alternative but much more destructive, would be to move all of the properties related to rate limiting from `BaseResponse` in their own class and remove their nullability - if the object exists, then they too exist - and possibly make `BaseResponse` generic to encapsulate the actual response received from Open AI, along with anything else we deem worthy.

This makes using the API a bit more cumbersome and entirely changes how users interact with it. You'd need to access 1 more property to get to what you're most interested it. The benefits are that it removes the need for throwing exceptions for normal execution flow, as well as users writing try/catches for normal execution flow. There's nothing uncommon or exceptional about requests with a status code of 400-499. A 500+ status code is an exceptional event though, as it indicates an unexpected server-side error and the client can do nothing to change its outcome.

First approach is much more manageable for implementation. It all depends on how much we value performance, versus simplicity and in which direction we should focus our time and effort on.

P.S: I'm willing to help out with anything you guys decide to do on this.

**Comment by StephenHodgson** [comment]
>  There's nothing uncommon or exceptional about requests with a status code of 400-499. A 500+ status code is an exceptional event though, as it indicates an unexpected server-side error and the client can do nothing to change its outcome.

and exception is exceptional. Idk personally I like try/catch as it gives me more control about how I want to handle any situation where I need to make a choice about how to handle it. Give more power to the consumer of the library.

**Comment by StephenHodgson** [comment]
> It all depends on how much we value performance, versus simplicity

It's a remote resource call, not sure we need the performance imho

**Comment by StephenHodgson** [comment]
tbh we need to have a more dedicated exception for the library itself that contains the data about the errors, data, etc when certain calls don't finish successfully. Low priority imho.

**Comment by kikaragyozov** [comment]
> I vote no on the Alternative, just to be clear

I'm not convinced the exception route is good in the long run. Handling 404 not found as an exception in a REST HTTP API world by a HTTP API library rather than returning a null object as a response to the consumers, "translating" if you may say the HTTP REST world to the .NET world, is much more appealing and manageable both for us and them.

Would you be okay if I tackled support for 429 via an exception while also addressing the 404 responses by returning a null object instead of throwing? I know it might look weird to start doing it both ways, but this way we're striking a good balance between ease of use and not overly complicated API design.

Do you agree? It's just very strange for me to get an exception when requesting a given entity, but that entity is no longer there, i.e it was deleted by someone else. I'd expect as a consumer to simply receive a null object as a response and then I'd know what's up and deal with it appropriately.

**Comment by StephenHodgson** [comment]
I don't understand why try/catch is a overcomplicated use of a native language feature.

**Comment by StephenHodgson** [comment]
I'm sorry but you're not going to convince me to change it to be this way 😅

**Comment by StephenHodgson** [comment]
I don't think your analogy is exactly 1:1.

I understand where you're coming from but at the same time I want this library to be as slim as possible, call giving developers options on how they want to handle the return codes.

**Comment by kikaragyozov** [comment]
> I don't think your analogy is exactly 1:1.
> 
> I understand where you're coming from but at the same time I want this library to be as slim as possible, call giving developers options on how they want to handle the return codes.

If OpenAI did not conform to the REST world, they'd just return you a `null` application/json response for the resource you're requesting. Would you still throw an exception then?
