### ISSUE TITLE
Question about DefaultRequestHeaders

### ISSUE THREAD

**Issue by fejdraus** [RageAgainstThePixel/OpenAI-DotNet#198]
Class "OpenAIClient".

Why is "client.DefaultRequestHeaders.Add("OpenAI-Beta", "assistants=v1");" always used? Because it is not needed for all requests, it is needed, for example, for assistants requests, but it is not needed for working with files.

Why is "OpenAI-DotNet" written in client.DefaultRequestHeaders.Add("User-Agent", "OpenAI-DotNet"); ? Maybe it would be better to make an optional fill?

**Comment by StephenHodgson** [comment]
I think the existing API endpoints are probably fine.

Besides I did have to make modifications to support the updated end points anyway.

**Comment by StephenHodgson** [comment]
If it turns out being more of a problem we can come back to this. But for now I'd rather leave it the way it is

**Comment by StephenHodgson** [comment]
I will consider it if it becomes a problem

**Comment by fejdraus** [comment]
All right. Thank you.

**Comment by StephenHodgson** [comment]
@fejdraus I actually did as you requested in latest release #489
