### ISSUE TITLE
thread.RetrieveRunAsync("run-id") does not find

### ISSUE THREAD

**Issue by fejdraus** [RageAgainstThePixel/OpenAI-DotNet#199]
var run = await thread.RetrieveRunAsync("run-id"); does not find RetrieveRunAsync in the namespace.

**Comment by StephenHodgson** [comment]
Sounds like you're missing a namespace using statement.

**Comment by StephenHodgson** [comment]
Is this from the example docs?

I'll double check but that might not actually be implemented.

**Comment by StephenHodgson** [comment]
Ah instead you can use `run.UpdateAsync();`

I'll update the docs

**Comment by fejdraus** [comment]
Thank you.

**Comment by StephenHodgson** [comment]
Gonna keep this open until I made the changes.

Thanks again!
