### ISSUE TITLE
CS0841 with sample code from readme.md

### ISSUE THREAD

**Issue by Onkitova** [RageAgainstThePixel/OpenAI-DotNet#200]
# Bug Report

## Overview
Line 870 of readme.md, where instead of:
```csharp
Console.Write(choice.Delta.ToString());
```
should be (probably):
```csharp
Console.Write(partialResponse.FirstChoice.Delta.ToString());
```

Otherwise we got CS0841 due to "Cannot use local variable 'choice' before it is declared"

**Comment by StephenHodgson** [comment]
Thanks for the catch I'll update the docs on next release
