### ISSUE TITLE
Thread Message content object is not compliant with openai API

### ISSUE THREAD

**Issue by Pizzajongen** [RageAgainstThePixel/OpenAI-DotNet#201]
[Threads.Content ](https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/main/OpenAI-DotNet/Threads/Content.cs) does not implement the openAI API correctly. It looks like it is assumed that the image content would be the same as in a regular [Chat.Content ](https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/main/OpenAI-DotNet/Chat/Content.cs) object. but instead of an [Common.ImageUrl ](https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/main/OpenAI-DotNet/Common/ImageUrl.cs) the Threads.Message object should contain an `ImageFile` object, containing only a `file_id` field  ([api docs](https://platform.openai.com/docs/api-reference/messages/object)).

**Comment by chadcts** [comment]
[0001-Added-missing-ContentType-image_file-and-associated-.patch](https://github.com/RageAgainstThePixel/OpenAI-DotNet/files/13593400/0001-Added-missing-ContentType-image_file-and-associated-.patch)

 Here's a patch.

**Comment by StephenHodgson** [comment]
So I've just been busy today haven't been able to knock this out
