### ISSUE TITLE
Add "gpt-4-1106-preview" and "gpt-4-vision-preview"

### ISSUE THREAD

**Issue by fejdraus** [RageAgainstThePixel/OpenAI-DotNet#205]
Please add "gpt-4-1106-preview" and "gpt-4-vision-preview" to the model selection.

**Comment by StephenHodgson** [comment]
No need to add, just use model id. Will add when out of preview

**Comment by ADefWebserver** [comment]
```
            // Get a response from ChatGPT 
            var FinalChatRequest = new ChatRequest(
                chatPrompts,
                model: "gpt-4-vision-preview",
                temperature: 0.0,
                topP: 1,
                frequencyPenalty: 0,
                presencePenalty: 0,
                responseFormat: ChatResponseFormat.Json);
```

**Comment by StephenHodgson** [comment]
> ```
>             // Get a response from ChatGPT 
>             var FinalChatRequest = new ChatRequest(
>                 chatPrompts,
>                 model: "gpt-4-vision-preview",
>                 temperature: 0.0,
>                 topP: 1,
>                 frequencyPenalty: 0,
>                 presencePenalty: 0,
>                 responseFormat: ChatResponseFormat.Json);
> ```

Don't forget if you're using Json format you need to put it in the system prompt.

**Comment by fejdraus** [comment]
That's cool. Thank you so much.
