### ISSUE TITLE
Enabling CodeInterpreter

### ISSUE THREAD

**Issue by Lermatroid** [RageAgainstThePixel/OpenAI-DotNet#207]
Hello,

I am attempting to enable code interpreter on a assistant I am creating however I cannot seem to figure out how to get this working and cannot find anything in the docs for the built in tools.

Thanks!

**Comment by StephenHodgson** [comment]
Just need to specify it as one of the tools when you create an assistant.

**Comment by Lermatroid** [comment]
Thanks! I am trying to go ahead and do that but the only docs on the syntax I can find is defining your own custom tools. I tried something like this to no avail based off the openAI docs.

```csharp
tools: new Tool[] { new Tool(type: "code_interpreter") }
```

**Comment by Lermatroid** [comment]
Just figured it out actually. This seems to be the syntax in case anyone else is having the issue in the future!

```csharp
tools: new Tool[] { Tool.CodeInterpreter }
```
