### ISSUE TITLE
HttpClient usage

### ISSUE THREAD

**Issue by jack0fshad0ws** [RageAgainstThePixel/OpenAI-DotNet#208]
# Possible issue with OpenAIClient HttpClient

## Overview
If OpenAIClient is not used as singleton it might run into issues with HttpClient like socket exhaustion etc. 

## To Reproduce
Create transient or request scope OpenAIClient with ctor defaults, which then creates and disposes (Http)Client in the same scope.
https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines#pooled-connections

## Question
Is OpenAIClient intended to be used as singleton only? Is it threadsafe?

If not, alternatives might be using HttpClientFactory or make `internal HttpClient Client { get; private set; }` static?
A workaround could be though to implement a factory that creates HttpClient externally and passes it to OpenAIClient factory created instance.

**Comment by StephenHodgson** [comment]
no it is not intended to be used as a singleton, which imho is a code smell practice that inexperienced devs use.

it is designed this was intentionally as OpenAI for Azure forces devs to have to create a new client for each model respectively (frustrating I know)

In either case, unless a provable bug case with proper repro steps can be provided, I am going to close this issue.
