### ISSUE TITLE
parameter naming of CreateMessageRequest in OpenAI.Threads

### ISSUE THREAD

**Issue by ludson** [RageAgainstThePixel/OpenAI-DotNet#219]
Issue Description 🔎
Context: I've noticed a potential discrepancy in the CreateMessageRequest class within the OpenAI.Threads namespace, specifically regarding the naming of a property.

Current Implementation 🐛
The class currently has a property named fieldIds. This is highlighted in the code snippet below:
```csharp
namespace OpenAI.Threads
{
public sealed class CreateMessageRequest
{
// ... other properties ...

[JsonPropertyName("file_ids")]
public IReadOnlyList<string> **FieldIds** { get; } // Note the naming here
```
Suggested Change 💡
However, based on the JsonPropertyName attribute ("file_ids"), it seems that the intended name for this property should be fileIds. This change could enhance clarity and reduce potential confusion in the code. Here's how it could look:
```csharp
namespace OpenAI.Threads
{
public sealed class CreateMessageRequest
{
// ... other properties ...
[JsonPropertyName("file_ids")]
public IReadOnlyList<string> FileIds { get; } // Updated naming
```
Recommendation 📝
I recommend reviewing and possibly updating the property name to ensure it aligns with its intended purpose, enhancing code readability and maintainability.

**Comment by StephenHodgson** [comment]
Product of dyslexia 🥴

**Comment by StephenHodgson** [comment]
Just to be clear the name of the property was ok. It was only the name of the parameter in the `.ctr` that was malformed.
