### ISSUE TITLE
Code interpreter input / output is not accessible via StepDetails

### ISSUE THREAD

**Issue by benjicoh** [RageAgainstThePixel/OpenAI-DotNet#224]
# Bug Report

## Overview
Code interpreter input / output is not accessible via StepDetails
as described here - https://platform.openai.com/docs/api-reference/runs/step-object

**Comment by StephenHodgson** [comment]
Looks like the API was updated. 

At the time of writing step details `ToolCalls` only returned functions
https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/54958d2e1832f13014e9a4b6346b27bef9dce459/OpenAI-DotNet/Threads/StepDetails.cs#L26
https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/54958d2e1832f13014e9a4b6346b27bef9dce459/OpenAI-DotNet/Threads/ToolCall.cs#L18

**Comment by benjicoh** [comment]
Maybe, since the api if pretty fluid right now add the entire response json to BaseResponse ?

**Comment by StephenHodgson** [comment]
> Maybe, since the api is kind of fluid right now add the entire response json (as plain string) to BaseResponse ?

Absolutely not
