### ISSUE TITLE
A member with the name 'name' already exists on 'OpenAI.Chat.Message'

### ISSUE THREAD

**Issue by MegaMax5000** [RageAgainstThePixel/OpenAI-DotNet#227]
# Bug Report
The following error message occurs when attempting ChatEndpoint.GetCompletionAsync():

JsonSerializationException: A member with the name 'name' already exists on 'OpenAI.Chat.Message'. Use the JsonPropertyAttribute to specify another name.

I apologize if this is not the proper space to bring this up, I could not start a discussion in the Q&A section of the Discussions tab. 

## Overview
Upon looking through the source I see that in Message.cs there is a serialized field "name" as well as using the JsonPropertyAttribute to specify the public "Name" field to serialize as "name".  This might be causing the issue. 

## To Reproduce
The following code reproduces this problem on the "await api.ChatEndpoint.GetCompletionAsync(chatRequest);" line.

```csharp
private async Task<string> SendMessage(string message)
{
    var api = new OpenAIClient(GPT_API_KEY);

    var messages = new List<Message>
    {
        new Message(Role.System, GPT_SYSTEM_ROLE),
        new Message(Role.User, message)
    };
    var chatRequest = new ChatRequest(messages, GPT_MODEL_ID);
    var response = await api.ChatEndpoint.GetCompletionAsync(chatRequest);
    var choice = response.FirstChoice;

    return choice.Message.Content.ToString();
}
```

## Expected behavior
I would expect that error to not occur and for the GetCompletionAsync() to complete as expected.

## Additional context
I am using this package in Unity 2022.3.10f1.

**Comment by StephenHodgson** [comment]
I don't understand. Are you using my official unity package or using the Nuget version in Unity?

**Comment by MegaMax5000** [comment]
Oh I'm sorry, yes I'm using that unity package. I must have posted on the wrong repo.

**Comment by MegaMax5000** [comment]
Created a new issue there: https://github.com/RageAgainstThePixel/com.openai.unity/issues/170
