### ISSUE TITLE
The response value of the function is out of order

### ISSUE THREAD

**Issue by shiweihu** [RageAgainstThePixel/OpenAI-DotNet#249]
# Bug Report
 [HttpPost]
    public async Task<IActionResult> MyPost([FromBody] Dictionary<int, string> myMap)
    {

        var messages = new List<Message>();
        foreach (var keyValue in myMap) {
            if (keyValue.Key == 3)
            {
                messages.Add(new Message(Role.User, keyValue.Value));
            }
            else {
                messages.Add(new Message(Role.Assistant, keyValue.Value));
            }
        }
        Response.ContentType = "text/plain";
        Response.Headers.Add("Cache-Control", "no-cache");
        Response.Headers.Add("Connection", "keep-alive");
        var chatRequest = new ChatRequest(messages);
        await foreach (var partialResponse in api.ChatEndpoint.StreamCompletionEnumerableAsync(chatRequest))
        {
            if (partialResponse.FirstChoice.Delta.Content != null && partialResponse.FirstChoice.Delta.Content != "")
            {
                var data = Encoding.UTF8.GetBytes(partialResponse.FirstChoice.Delta.Content);
                Console.Write(partialResponse.FirstChoice.Delta.Content);
                //await Response.Body.WriteAsync(data, 0, data.Length);
                //await Response.Body.FlushAsync();
            }
        }
        //await Response.BodyWriter.CompleteAsync();
        return new EmptyResult();
    }
    
    it is my asp.net code. Console.Write print the text from te steam,and it is out of order.

**Comment by StephenHodgson** [comment]
What version was this?

**Comment by shiweihu** [comment]
the least, i update 5 minuts ago. ASP.NET SDK is 7

**Comment by ADefWebserver** [comment]
Perhaps it actually comes from OpenAI out of order?

**Comment by StephenHodgson** [comment]
Is there not a stack trace? 
I only see your example

**Comment by StephenHodgson** [comment]
> Perhaps it actually comes from OpenAI out of order?

I think the fact that the order matters, is more or less a problem with your implementation. Since it's Jason most of the objects are unordered by their nature.

**Comment by shiweihu** [comment]
ok,is the masssage list contains chat historical?
i mean should i push the historical chat into the massage list?

**Comment by ADefWebserver** [comment]
This line could prevent an item from being returned and then later it passes this check but now things seem 'out of order'
`if (partialResponse.FirstChoice.Delta.Content != null && partialResponse.FirstChoice.Delta.Content != "")`

**Comment by shiweihu** [comment]
however, i test it only with one message.
the message is “write a android compose example code”.
and it response：
Here is an example code snippetHere is using Android an example Compose:

```kotlin
import androidx.compose of a.foundation.layout basic Android Compose code snippet:

```kotlin
import androidx.compose.Column
.foundation.layout.Column
import androidximport androidx.compose.material.Text
.compose.materialimport androidx.Text
import androidx.compose.runtime.compose.runtime.Composable
.Comimportposable
import androidx.compose androidx.compose.ui.tooling.ui.tool.preview.Preview

ing.preview.Preview@Com
importposable
fun My androidx.composeComposable.ui.toolComponent() {
    Column {
ing.preview        Text(text =.P "Helloreview, AndroidParameter

@Com Compose!")
       posable
 Text(textfun G = "reetUser(name:This is a sample String) {
    Composable Text(text = " component.")
    }
}

@Hello,Preview
 $name@Com!")
}

@Previewposable
fun
 Preview@MyComposableComponentComposable
fun() {
    My PreviewGComposableComponent()
reetUser() {
}
```

In    G this codereetUser snippet, we define(name = a Com "Johnposable function")
}
 `My```

ComposableComponent`In this that displays two ` example,Text we have` elements within a com a `posable functionColumn` `G layout.reetUser` that We also use the `@ takes aPreview` annotation to `name create a` parameter preview function and displays a greeting `PreviewMyCom message.posableComponent We have` that also created a preview allows us function ` to see how thePreviewGreetUser Composable component will look like` to show how in the Android Studio the com preview paneposable looks.

**Comment by shiweihu** [comment]
you can see that the order of output is chaotic.
