### ISSUE TITLE
Add support for streaming with the assistants API

### ISSUE THREAD

**Issue by Mitch528** [RageAgainstThePixel/OpenAI-DotNet#267]
# Feature Request

Add support for streaming with the assistants API

## Additional context
https://platform.openai.com/docs/assistants/overview/step-4-create-a-run?context=with-streaming

**Comment by Mitch528** [comment]
> They still haven't added it to the OpenAPI spec yet
> 
> https://github.com/openai/openai-openapi

@StephenHodgson 

Odd. It has been added to their node client though (https://github.com/openai/openai-node/commit/7d27d286876d0a575d91a4752f401126fe93d2a3).

API docs have also been updated https://platform.openai.com/docs/api-reference/assistants-streaming

**Comment by rumrunner0** [comment]
Hi everyone. It seems the streaming feature for the Assistant API has just been released. Is it possible to start working on its support?

**Comment by StephenHodgson** [comment]
> Hi everyone. It seems the streaming feature for the Assistant API has just been released. Is it possible to start working on its support?
> 
> Here is the start point https://platform.openai.com/docs/api-reference/assistants-streaming

See previous reply about OpenAI OpenAPI document not being updated yet. I use that document as input for source generator.

**Comment by StephenHodgson** [comment]
https://github.com/openai/openai-openapi/issues/208

**Comment by StephenHodgson** [comment]
So it seems they actually use a completely different API surface for this which is quite a breaking change.

So I won't be adding this until 8.0.0
