### ISSUE TITLE
Tool/Function - Potential Memory Leak and Concurrency Problem.

### ISSUE THREAD

**Issue by r-Larch** [RageAgainstThePixel/OpenAI-DotNet#273]
## Why does the `Function.FromFunc(..)` store a ref to the `Instance` to a static cache?

Line: `functionCache[Name] = this; ` The `this` object hast a ref to `object instance`.

https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/9124a333235cc64f725357e439faacc2718ac7ce/OpenAI-DotNet/Common/Function.cs#L78-L91

The `object instance` for the `MethodInfo` can be an object that's only valid inside the calling method.

Imagine this example:
```csharp
public void Test(int id) {
  var myService = new MyService(id); // Instance only valid inside this method!
  var request = new ChatRequest(
      messages: history,
      model: "gpt-4-0125-preview",
      toolChoice: "auto",
      tools: [
          Tool.FromFunc("test", (string search) => myService.GetData(search)), // lambda produces a compile-time generated wrapper class instance where a ref to myService is stored.
      ]
  );
}
```

This example has two problems:
- It keeps `myService` endlessly in memory
- It has a Concurrency Problem.

**Concurrency Problem**

Imagine concurrently calling `Test(int id)` from different threads with different values for `id`.
Eg. inside an ActionMethod that will be called from two HttpRequest simultaneously.

In this case, the first request will store its `myService` instance in `functionCache[Name]` and the second will overwrite `functionCache[Name]` with its `myService` instance leading to unexpected behavior.

## Can we remove/fix the static cache?

Maybe changing `Function.Invoke..` to accept instance parameter so that only a MethoInfo gets stored and cached inside the Function.

**Comment by StephenHodgson** [comment]
Pretty sure you can remove and clear the cache which should release the reference to `this` object.

**Comment by r-Larch** [comment]
The cache is `private static readonly` I can not access it to call clear.
Even if I were able to call clear, a concurrency problem would remain.
I depend on using Tools/Functions concurrently like in the example.

https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/9124a333235cc64f725357e439faacc2718ac7ce/OpenAI-DotNet/Common/Function.cs#L237

**Comment by r-Larch** [comment]
This test shows the concurrency problem:

```csharp
[Test]
public void Test_03_Tool_works_when_called_concurrently()
{
    Assert.Multiple(async () => {
        await Task.WhenAll(
            Test(1),
            Test(2),
            Test(3),
            Test(4)
        );
    });

    async Task Test(int id)
    {
        var tool = Tool.FromFunc("myFunc", () => id, "This func allows reading the local variable id");

        // Delay a little bit to simulate calling OpenAi API:
        await Task.Delay(50);

        var result = tool.InvokeFunction<int>();
        Assert.AreEqual(id, result);
    }
}
```

Result:

```
Multiple failures or warnings in test:
  1)   Expected: 3
  But was:  4
   
  2)   Expected: 1
  But was:  4
  
  3)   Expected: 2
  But was:  4
```

**Comment by r-Larch** [comment]
To remove the static cache, I think it is required to change the public API.

I would suggest an API like the following:
- Reduce `Tool` and `Function` to plain POCO and use `ToolCall` POCO for tool calls.
- Introduce something like `ToolCollection` and `ToolFunction` to do all the reflection and to store instance references.
- Let `ToolCollection` implement `IEnumerable<Tool>` to be able to assign it to request tools.
- Use the locally living ToolCollection instance to execute the ToolCalls.
- [Extra]: As a performance improvement, `ToolCollection` could cache the reflection work done for a `MethodInfo`.

```csharp
// Create a collection of tool functions
// The lifecycle of a ToolCollection should be short, not statically cached.
// A ToolFunction may contain a static cache, but only for `MethodInfo` reflection work and not for the `Func<..>.Target` instance.
var tools = new ToolCollection {
    new ToolFunction("myFunc1", () => someMethod(), "Some description"),
    new ToolFunction("myFunc2", () => anotherMethod(), "Another description"),
};

// Define a request with the tool collection
var request = new ChatRequest(
    messages: history,
    model: "gpt-4-0125-preview",
    toolChoice: "auto",
    tools: (IEnumerable<Tool>) tools
);

// Asynchronously get a response from the chat endpoint
var response = await client.ChatEndpoint.GetCompletionAsync(request, cancellationToken);

// Process each tool call in the response
foreach (var toolCall in response.FirstChoice.Message.ToolCalls)
{
    string result = tools.Invoke(toolCall);
    history.Add(new Message(toolCall, result));
}
```

**Comment by StephenHodgson** [comment]
> The cache is `private static readonly` I can not access it to call clear. Even if I were able to call clear, a concurrency problem would remain. I depend on using Tools/Functions concurrently like in the example.
> 
> https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/9124a333235cc64f725357e439faacc2718ac7ce/OpenAI-DotNet/Common/Function.cs#L237

There is a method to clear all tools:

https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/9124a333235cc64f725357e439faacc2718ac7ce/OpenAI-DotNet/Common/Tool.cs#L118

**Comment by StephenHodgson** [comment]
> This test shows the concurrency problem:
> 
> ```cs
> [Test]
> public void Test_03_Tool_works_when_called_concurrently()
> {
>     Assert.Multiple(async () => {
>         await Task.WhenAll(
>             Test(1),
>             Test(2),
>             Test(3),
>             Test(4)
>         );
>     });
> 
>     async Task Test(int id)
>     {
>         var tool = Tool.FromFunc("myFunc", () => id, "This func allows reading the local variable id");
> 
>         // Delay a little bit to simulate calling OpenAi API:
>         await Task.Delay(50);
> 
>         var result = tool.InvokeFunction<int>();
>         Assert.AreEqual(id, result);
>     }
> }
> ```
> 
> Result:
> 
> ```
> Multiple failures or warnings in test:
>   1)   Expected: 3
>   But was:  4
>    
>   2)   Expected: 1
>   But was:  4
>   
>   3)   Expected: 2
>   But was:  4
> ```

This makes sense, because you're not calling each task concurrently. You are putting them into a collection and running each in their own context.

**Comment by StephenHodgson** [comment]
> To remove the static cache, I think it is required to change the public API.

Sorry that just isn't going to happen. This was a deliberate design choice to reduce memory consumption while giving api consumers control over the cache.

At best, I can add a way to remove a specific tool from the cache, since that seems to be the only missing convenience method.

**Comment by StephenHodgson** [comment]
Sorry I didn't mean to close the issue.

**Comment by r-Larch** [comment]
> > The cache is `private static readonly` I can not access it to call clear. Even if I were able to call clear, a concurrency problem would remain. I depend on using Tools/Functions concurrently like in the example.
> 
> There is a method to clear all tools:
> 
> https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/9124a333235cc64f725357e439faacc2718ac7ce/OpenAI-DotNet/Common/Tool.cs#L118

This method clears the tool cache but not the function cache.
The function cache contains the reference to the instance in question.

**Comment by StephenHodgson** [comment]
I'll take a look at the function cache and make sure it is properly getting cleaned up when the associated tool is also removed.

**Comment by r-Larch** [comment]
> This makes sense, because you're not calling each task concurrently. You are putting them into a collection and running each in their own context. The problem is with the implementation of your test. If you wanted to run these concurrently then it should be a for loop and await each Test call.
> 
> ```cs
> [Test]
> public async Task Test_03_Tool_works_when_called_concurrently()
> {
>     for (int i = 0; i < 5; i++)
>     {
>         await Test(i);
>     }
> 
>     async Task Test(int id)
>     {
>         var tool = Tool.FromFunc("myFunc", () => id, "This func allows reading the local variable id");
> 
>         // Delay a little bit to simulate calling OpenAi API:
>         await Task.Delay(50);
> 
>         var result = tool.InvokeFunction<int>();
>         Assert.AreEqual(id, result);
>     }
> }
> ```

Awaiting an async function means waiting until all work in this function has been done and the function has returned.
This means awaiting the same function in a loop has the same effect as calling the function synchronously one after the other.

Concurrently means at the same time. This means multiple threads enter the function at the same nanosecond and execute each line almost simultaneously and yes, each thread has its own context and its own call stack but they all share the same heap. And on the heap lies the static cache.

I intended to test concurrency as defined in this definition because when using chat completion with tools on a server to serve an http request each http request has its own thread and context and it is very likely to have multiple requests to the same url at the same nanosecond.

And as my test shows, there is a problem.
And this problem makes the whole tool API design not working in a multi threaded environment with tool-functions that can only live within the scope of a method, thread or http request.

**Comment by StephenHodgson** [comment]
I don't think your test is testing what you're trying to test

**Comment by StephenHodgson** [comment]
I think I do understand what you're trying to point out though.

**Comment by r-Larch** [comment]
> I don't think your test is testing what you're trying to test

My test is exactly testing concurrent execution.
Please read the definition of `Task.WhenAll`:

https://blog.stackademic.com/using-task-whenall-in-c-a-comprehensive-guide-with-examples-d7e42ddf3485#:~:text=The%20Task.WhenAll%20method%20is%20a%20powerful%20tool%20for%20concurrently%20executing%20multiple%20tasks%20and%20awaiting%20their%20completion.

> The Task.WhenAll method is a powerful tool for concurrently executing multiple tasks and awaiting their completion.

**Comment by StephenHodgson** [comment]
Ok, after doing some more digging into this, it looks like each func you're registering is getting replaced by one of the other ones, bc the keys are not entirely unique in the cache, which explains the behavior you're seeing. I believe that is the real cause of the problem, and will look into addressing this in the future.

**Comment by StephenHodgson** [comment]
I was able to verify my last comment was indeed the issue. I added the id to the func name and it seems to pass with your original test case:

```csharp
[Test]
public void Test_03_Tool_works_when_called_concurrently()
{
    Assert.Multiple(async () => {
        await Task.WhenAll(
            Test(1),
            Test(2),
            Test(3),
            Test(4)
        );
    });

    async Task Test(int id)
    {
        var tool = Tool.FromFunc($"myFunc_{id}", () => id, "This func allows reading the local variable id");

        // Delay a little bit to simulate calling OpenAi API:
        await Task.Delay(50);

        var result = tool.InvokeFunction<int>();
        Assert.AreEqual(id, result);
    }
}
```

I will add a check if func name is already registered and throw an exception if so.

**Comment by r-Larch** [comment]
This fix shows to me the problem at hand is by design. Having to dynamically change a function name to prevent collisions in a static cache sounds terrible and cannot be used as a production-ready fix. I appreciate the effort put into this, and I'm looking forward to a more sustainable solution.

**Comment by StephenHodgson** [comment]
The fix shows you didn't understand the problem to begin with.

Had nothing to do with memory or concurrency.

If you don't like it you can use another package.
You seem awfully ungrateful to somebody that puts in a lot of their own free time to make things like this.
