### ISSUE TITLE
Unknown parameter tool_calls index on gpt-4-turbo

### ISSUE THREAD

**Issue by Mitch528** [RageAgainstThePixel/OpenAI-DotNet#278]
# Bug Report

## Overview
When using a tool call in a chat request, the API returns an error that index is an unknown parameter.

This occurs in gpt-4-turbo (non preview)

## To Reproduce

Modify the test `Test_02_03_ChatCompletion_Multiple_Tools_Streaming` to use `gpt-4-turbo`

## Expected behavior
The API to not return an error

**Comment by StephenHodgson** [comment]
Gonna need more info than this, sorry.

What does your tool setup look like?
Sounds like the tool list malformed.

**Comment by StephenHodgson** [comment]
wasn't able to reproduce this when using new gpt-4-turbo model

**Comment by Mitch528** [comment]
> wasn't able to reproduce this when using new gpt-4-turbo model

@StephenHodgson 

seems like OpenAI must have reverted the change that caused the error. However, it appears that `index` is still an invalid parameter so it may be ideal to remove it from `tool_calls`.

see https://community.openai.com/t/gpt-4-turbo-model-function-call-doesnt-work/712218/4

**Comment by StephenHodgson** [comment]
Ok, I'll keep testing and fix anything I come across
