### ISSUE TITLE
Chat Completions (gpt-3.5-turbo)

### ISSUE THREAD

**Issue by ADefWebserver** [RageAgainstThePixel/OpenAI-DotNet#28]
# Feature Request

## Is your feature request related to a problem? Please describe.
OpenAI has released [chat completions](https://platform.openai.com/docs/guides/chat/chat-completions-beta)

## Describe the solution you'd like
Support the new endpoint and the messages model

**Comment by StephenHodgson** [comment]
I'm literally in the middle of it right now lol

**Comment by ADefWebserver** [comment]
...because you know I was going to do a PR if you weren't... 😉

**Comment by StephenHodgson** [comment]
I'm just finishing up the docs now, want to give it a once over before we release?

**Comment by ADefWebserver** [comment]
Yes!!

**Comment by ADefWebserver** [comment]
Give me 24 hours...
