### ISSUE TITLE
Assistants Beta V2

### ISSUE THREAD

**Issue by StephenHodgson** [RageAgainstThePixel/OpenAI-DotNet#285]
OpenAI has released a new version of the Assistants, which significantly changes the API surface.

[Migration Guide](https://platform.openai.com/docs/assistants/migration)

Subtasks:

- [x] Add support for GPT-4o
- [x] #284 
- [x] #267

**Comment by StephenHodgson** [comment]
I wasn't planning on tracking these individually.

**Comment by StephenHodgson** [comment]
> I wonder if there is some way we could consume the OpenAI API spec so that when new properties get released it can be partially automated?
> 
> https://github.com/openai/openai-openapi/blob/master/openapi.yaml

I already have something locally that I use, but it's not good enough for all the edgecases.

**Comment by marcusx2** [comment]
For anyone wondering how to patch this package to support Assistants Beta V2, here's what I did

1. Have the author's package in the asset folder so it's editable.
2. To patch the header without changing the author's package, there's a small reflection trick that can be done

```
var dictionary = (Dictionary<string, string>)client.DefaultRequestHeaders;
dictionary["OpenAI-Beta"] = "assistants=v2";
client.GetType().GetProperty(nameof(client.DefaultRequestHeaders)).SetValue(client, dictionary);
```

3- Now you have to use the [tool_choice](https://platform.openai.com/docs/api-reference/runs/createThreadAndRun#runs-createthreadandrun-tool_choice) field otherwise your assistant will just ignore the knowledge files you provide. To do this, 
modify the CreateRunAsync method under ThreadExtensions.cs to

```
public static async Task<RunResponse> CreateRunAsync(this ThreadResponse thread, string assistantId, object toolChoice = null, CancellationToken cancellationToken = default)
            => await thread.Client.ThreadsEndpoint.CreateRunAsync(thread, new CreateRunRequest(assistantId, toolChoice), cancellationToken);
```

And CreateRunRequest.cs class, modify the bigger constructor to be


```
[Preserve]
        public CreateRunRequest(string assistantId, object toolChoice = null, string model = null, string instructions = null, IEnumerable<Tool> tools = null, IReadOnlyDictionary<string, string> metadata = null, float? temperature = null) {
            AssistantId = assistantId;
            ToolChoice = toolChoice;
            Model = model;
            Instructions = instructions;
            Tools = tools?.ToList();
            Metadata = metadata;
            Temperature = temperature;
        }
```

and add the property

```
[Preserve]
        [JsonProperty("tool_choice")]
        public object ToolChoice { get; }
```

I chose the "object" type because ToolChoice can be a string, or a dictionary, and JSONNet just takes care of the rest.


Hacky but works.

**Comment by devonuto** [comment]
@StephenHodgson I set up a test project and it's having issues, would changes to the Assistant be the reason I'm getting this error:

```
System.ObjectDisposedException: 'Cannot access a disposed object.
Object name: 'System.Net.Http.HttpClient'.'
```

when it gets to await assistant.CreateThreadAndRunAsync(threadRequest); in this:

```
  var assistantName = _configuration["OpenAIAssistant"];
        var assistant = (await ListAssistants()).FirstOrDefault(x => x != null && x.Name == assistantName);
        if (assistant == null)
        {
            assistant = await CreateAssistant();
        }
        else if (assistant.Instructions != _instructions)
        {
            var modifyRequest = new CreateAssistantRequest(
                name: assistant.Name,
                model: assistant.Model,
                instructions: _instructions
            );
            assistant = await assistant.ModifyAsync(modifyRequest);
        }

        if (assistant != null)
        {
            using var api = new OpenAIClient();
            var messages = new List<Message>() { "hello" };
            var threadRequest = new CreateThreadRequest(messages);
            await assistant.CreateThreadAndRunAsync(threadRequest);
        }
```

Or should I raise this as a new issue?

**Comment by minzdrav** [comment]
Hi @StephenHodgson 
Thank you for the great library!
OpenAI has released gpt-4o model and it's not compatible with Assistants v1 API. Throwing error:
`
{
    "message": "The requested model 'gpt-4o' cannot be used with the Assistants API in v1. Follow the migration guide to upgrade to v2: https://platform.openai.com/docs/assistants/migration.",
    "type": "invalid_request_error",
    "param": "model",
    "code": "unsupported_model"
  }
`
Is it possible to generate a library with Assistants v2?

**Comment by StephenHodgson** [comment]
Sorry I haven't had time to get around to it. 

I'll see what I can do this weekend.

**Comment by edvanr** [comment]
I'm also happy to help but I might need a quick kick off with you on the best way to approach some of these changes. I'll ping you on Discord

**Comment by StephenHodgson** [comment]
Most of the work is done. Just finishing up streaming support and fixing a few bugs with tool cache

**Comment by delsoul** [comment]
> Большая часть работы сделана. Просто завершаю поддержку потоковой передачи и исправляю несколько ошибок с кешем инструментов.

Hello! When can we expect GPT-4o support? Considering that most of the work has already been completed.
