### ISSUE TITLE
Allow default headers to be edited

### ISSUE THREAD

**Issue by marcusx2** [RageAgainstThePixel/OpenAI-DotNet#286]
# Feature Request

## Is your feature request related to a problem? Please describe.
OpenAI is constantly changing. Perhaps making the library more flexible would be beneficial for the user. To use the new OpenAI api, this header is necessary for example

<img width="431" alt="image" src="https://github.com/RageAgainstThePixel/OpenAI-DotNet/assets/5656275/42541323-3ee0-49da-9801-3f1b87bd6666">

However, when using this library, the v1 is used instead. Sure, you will update the library eventually to use v2, but it would be nice if the user could just change this if the default headers was not a readonlydictionary.

## Describe the solution you'd like
Editable headers.

**Comment by StephenHodgson** [comment]
Sorry, but I will not allow the default headers to be edited.
