### ISSUE TITLE
TestFixture_00_Authentication fails

### ISSUE THREAD

**Issue by ADefWebserver** [RageAgainstThePixel/OpenAI-DotNet#30]
# Bug Report

## Overview
TestFixture_00_Authentication fails 

## To Reproduce
1. Enter OPENAI_API_KEY and OPENAI_ORGANIZATION_ID in environment variables
2. Run Tests
3. Get:
Test_01_GetAuthFromEnv
   Source: TestFixture_00_Authentication.cs line 21
   Duration: 47.3 sec

  Message: 
  Expected: null
  But was:  "{{ my org key }}"

## Expected behavior
test should pass

**Comment by StephenHodgson** [comment]
This isbl definitely working. Likely you have not set all the system variables

**Comment by ADefWebserver** [comment]
But the test is expecting the value to be null?

`Assert.IsNull(auth.OrganizationId);`

**Comment by StephenHodgson** [comment]
Oh I see we can probably remove that check
