### ISSUE TITLE
Support calls to GPT-4o

### ISSUE THREAD

**Issue by Mark-Robinson** [RageAgainstThePixel/OpenAI-DotNet#302]
Please add support to the framework so that the newly released [GPT4o](https://platform.openai.com/docs/models/gpt-4o) model can be called. Initially, just being able to use GPT4o for chat requests would be a benefit due to its 2x performance and 0.5x price compared to GPT4 Turbo.

**Comment by StephenHodgson** [comment]
You can already use the model for ChatRequests. Assistant support will come in 8.0.0

**Comment by ADefWebserver** [comment]
> You can already use the model for ChatRequests

https://github.com/AIStoryBuilders/AIStoryBuildersOnline/commit/072bf4cb09be56d21234c716e3b55f8382e6476e
