### ISSUE TITLE
Unable to add open ai default tools as they become available

### ISSUE THREAD

**Issue by chronicadventure** [RageAgainstThePixel/OpenAI-DotNet#304]
# Feature Request

## Is your feature request related to a problem? Please describe.
Open AI's assistants now use a tool called "file_search" while this SDK only provides tools "retrieval" and "code_interpreter" there should be a way we can simply add a new tool so the SDK doesn't have to catch up. 

## Describe the solution you'd like
Perhaps a constructor on the `Tool` class that lets us set the `string Type` property as this property has a private setter.

## Describe alternatives you've considered
This is how I'm setting it now.
```
   var fileSearch = new Tool();
        
        var prop = typeof(Tool).GetProperty("Type", BindingFlags.Instance | BindingFlags.NonPublic);
        prop?.SetValue(fileSearch, "file_search", null);
```

## Additional context
This temporary solution is based off what I see for the default tools and how they are constructed in the SDK. for example

```
 public static Tool Retrieval { get; } = new Tool()
    {
      Type = "retrieval"
    };
```

**Comment by StephenHodgson** [comment]
Already scoped for change in [8.0.0](#285)
