### ISSUE TITLE
Possible to support more framework?

### ISSUE THREAD

**Issue by pikkenix** [RageAgainstThePixel/OpenAI-DotNet#312]
Is it possible to support more .net framework versions?

Our project is running .net framework 4.8 and cannot install via nuget. 
Is it possible to add support for .NET Framework v4.6.1 or Netstandard 2.0?

Best regards
Daniel

**Comment by StephenHodgson** [comment]
No I specifically didn't want to Target these tell him that the number of dependencies the project was depend on.

**Comment by StephenHodgson** [comment]
Specifically I didn't want to deal with Newtonsoft vs System.Text.Json and supporting either/both of these serialization libraries at the same time.
