### ISSUE TITLE
Chat completion: invoking functions from a streaming result throws exception

### ISSUE THREAD

**Issue by sibbl** [RageAgainstThePixel/OpenAI-DotNet#317]
# Bug Report

## Overview

When streaming a chat completion, I collect the whole response before invoking a function tool.

However, when invoking the function, I always get a "Failed to find a valid parameter name for ..." exception.

When taking a look at the JsonNode containing the result from the OpenAI API tool call, it can be seen that the root element of the function parameters is not a JSON object but a string, containing the stringified JSON object. Thus, the serialization only returns the string and not the object.

When using the non-streaming API, this works without any flaws.

## To Reproduce

1. Create a chat request with a tool function with one parameter, i.e. `string firstName`
2. Make a chat completion in streaming mode, invoking the tool function. Await the whole response and collect the tool calls.
3. Iterate over the tool calls and invoke them
4. `Failed to find a valid parameter name for firstName` will be thrown.

## Expected behavior

The function can be invoked properly.

**Comment by StephenHodgson** [comment]
Do you have a more complete code snippet example to reproduce this?

I'll add it to the unit tests as well.

**Comment by sibbl** [comment]
Please see this sample:

```
using OpenAI;
using OpenAI.Chat;

var client = new OpenAIClient(new OpenAIAuthentication("OPENAI_API_KEY"));

var messages = new List<Message>
{
    new Message(Role.System, "You must extract the name from the input"),
    new Message(Role.User, "My name is Joe")
};

var tools = new List<Tool>
{
    Tool.FromFunc("extract_first_name", (string name) => name)
};

var request = new ChatRequest(messages, tools);

var response = await client.ChatEndpoint.GetCompletionAsync(request);

foreach (var tool in response.FirstChoice.Message.ToolCalls)
{
    var output = tool.InvokeFunction<string>();
    Console.WriteLine($"Output from GetCompletionAsync: {output}");
}

await foreach (var streamResponse in client.ChatEndpoint.StreamCompletionEnumerableAsync(request))
{
    if (streamResponse.FirstChoice.Message is { } message)
    {
        foreach (var tool in message.ToolCalls)
        {
            var output = tool.InvokeFunction<string>();
            Console.WriteLine($"Output from StreamCompletionEnumerableAsync: {output}");
        }
    }
}
```

I actually don't know what's the best solution. For now, I just get the `tool.Function.Arguments.ToJsonString()`, deserialize it into a `string` and then deserialize this string into the object I need. Feels kind of ugly, so perhaps you got some better idea.

**Comment by StephenHodgson** [comment]
Thanks! I'll look into this and make sure it is addressed in 8.0.0

**Comment by StephenHodgson** [comment]
@sibbl I was able to fix this by specifying the func<T> specifically

```csharp
            var tools = new List<Tool>
            {
                Tool.FromFunc<string, string>("extract_first_name", name => name)
            };
```

I'm looking at a way to make sure it works the other way you defined as well. But it is a valid work around in the meantime.

**Comment by StephenHodgson** [comment]
part of the problem it seems is that OpenAI is returning a string encoded like this for me:

```
"\"{\\u0022name\\u0022:\\u0022Joe\\u0022}\""
```
