### ISSUE TITLE
Tool auto generated Invoke reflection names are too long

### ISSUE THREAD

**Issue by StephenHodgson** [RageAgainstThePixel/OpenAI-DotNet#323]
@StephenHodgson I've found that Assistant v2 doesn't always understand well when type.FullName is included, because the namespaces I use are long and not relevant/confusing to the AI context.
I found that removing this and only including the `method.Name` solved it.

I realize it isn't the ideal scenario in case two types contain the same method name, but it would still be helpful with an `omit namespace` option if possible. For now I've been removing it manually here in each update :)

_Originally posted by @Bodekaer in https://github.com/RageAgainstThePixel/com.openai.unity/pull/235#discussion_r1632762450_

## Proposed fix:

Converting long namespace names to hash file string guid.

**Comment by sagos95** [comment]
I faced the same issue.

> I found that removing this and only including the method.Name solved it.

But how did you do that? I didn't see any accessible ways to specify function name by myself.
By the way that could be a fix too - to allow users manually specify function names. As for me it will be not the best solution to use hashes or guids.

**Comment by StephenHodgson** [comment]
Using hashes or guids would make it a bit more difficult to debug.

**Comment by StephenHodgson** [comment]
> By the way that could be a fix too - to allow users manually specify function names.

Needs to be unique, and ideally not something that is super configurable, also the cache uses the names as keys on the backend.

**Comment by sagos95** [comment]
> also the cache uses the names as keys on the backend

Maybe it makes sense to separate Tools for different chats. For example, we could create a kind of Tool pool or Tool container. Making this class static provides a simpler way to interact with it, but this approach limits the flexibility of using Tools in scaled production apps.

**Comment by StephenHodgson** [comment]
You don't have to use the built-in tool definitions. You can always serialize and pass your own. 

The reason it is done this way is to provide convenient way to invoke those same tools if they happen to have locally defined methods you can execute in known libraries. Without mapping these things correctly it'd never work.
