### ISSUE TITLE
Whisper

### ISSUE THREAD

**Issue by ADefWebserver** [RageAgainstThePixel/OpenAI-DotNet#34]
# Feature Request

## Is your feature request related to a problem? Please describe.
Support OpenAI Whisper

## Describe the solution you'd like
OpenAI has released [Whisper](https://platform.openai.com/docs/models/whisper) and I would like this library to support it

## Additional context
I am willing to submit a PR

**Comment by StephenHodgson** [comment]
@ADefWebserver Just got back into the office today. I might have it done before then tbh
