### ISSUE TITLE
Not possible to instantiate a Tool with `Tool.Id` and `Tool.Function.Arguments` set?

### ISSUE THREAD

**Issue by henduck** [RageAgainstThePixel/OpenAI-DotNet#340]
## Context: 
The system I am working on requires that we be able to serialize the conversation history out to a database, then deserialize that history later on to resume the conversation with full history included.

## The problem: 
There does not appear to be a way to properly inflate a 'Tool' instance to recreate a history containing a function call and response, as there's no way to set the Tool.Id and/or Function.Arguments properties from outside of the OpenAI-DotNet library, as all requisite setters are private/internal, and I can't seem to find any other alternative way to do this.

## Example:
The following message payload was received from the OpenAI API, initiating a function call to the 'web-search' function. That's all working fine, as the OpenAI-DotNet library is able to deserialize and call internal/private setters for 'Id' and 'Function.Arguments', and so I can use that Tool instance while I still have a reference to it in-memory.
```json
{
    "role": "assistant",
    "content": null,
    "tool_calls": [
        {
            "id": "call_q9Zh5uG7iNXD3APBcwHd9Wwc",
            "type": "function",
            "function": {
                "name": "web-search",
                "arguments": "{\"query\":\"current population of New Jersey\"}"
            }
        }
    ]
}
```
However, if I serialize that out... then later want to re-inflate this conversation history to resume it, there is no way to properly set those properties... and so we cannot properly re-run this history for subsequent messages, as the closest we can get to re-inflating this message via code is:
```json
{
  "role": "assistant",
  "content": null,
  "tool_calls": [
    {
      "type": "function",
      "function": {
        "name": "web-search"
      }
    }
  ]
}
```
The tool's `id` and `function.arguments` are missing. And as such, we'll end up getting errors from the API, like:
```
{
    "error": {
        "message": "Missing required parameter: 'messages[2].tool_calls[0].id'.",
        "type": "invalid_request_error",
        "param": "messages[2].tool_calls[0].id",
        "code": "missing_required_parameter"
    }
}
```
Is there some alternative way to deserialize or manually re-create a conversation history in code to address this situation?

Thanks in advance, and thanks for this great library!

**Comment by StephenHodgson** [comment]
I'll take a look and see what I can do
