### ISSUE TITLE
Azure endpoints broken since version 8.2.0

### ISSUE THREAD

**Issue by sibbl** [RageAgainstThePixel/OpenAI-DotNet#349]
When performing a chat completion, a "404 not found" exception is thrown.

This is because since version 8.2.0 the URL `https://{resourceName}.openai.azure.com/openai/chatdeployments/{deploymentId}//completions?api-version={apiVersion}` is generated in here: https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/1a5a4975413e34c6be0eefe082b4da1784530089/OpenAI-DotNet/Common/OpenAIBaseEndpoint.cs#L42-L49

It should be

```csharp
if (client.OpenAIClientSettings.IsAzureOpenAI && IsAzureDeployment == true)
{
    route = $"deployments/{client.OpenAIClientSettings.DeploymentId}/{Root}{endpoint}";
}
else
{
    route = $"{Root}{endpoint}";
}
```

instead.

**Comment by StephenHodgson** [comment]
Sorry about that!

I didn't have a way to test this

**Comment by sibbl** [comment]
Thanks for the very quick completion of the PR! 

Unfortunately I didn't have the time yet to bump the version, but was happy to see that the release was already published.

Can confirm that it's working now.

**Comment by StephenHodgson** [comment]
I'll add some more unit tests for this as well in 8.2.2
