### ISSUE TITLE
Add Realtime implementation

### ISSUE THREAD

**Issue by StephenHodgson** [RageAgainstThePixel/OpenAI-DotNet#371]
- https://openai.com/index/introducing-the-realtime-api
  - https://platform.openai.com/docs/api-reference/realtime-client-events
  - https://platform.openai.com/docs/api-reference/realtime-server-events
- https://github.com/openai/openai-openapi/issues/341

**Comment by davidmigloz** [comment]
For reference:
https://github.com/openai/openai-dotnet/pull/238/

**Comment by StephenHodgson** [comment]
meh, for reference only. Not a fan of their implementation tbh.
