### ISSUE TITLE
When using Structured Outputs, only strings fields are marked as required

### ISSUE THREAD

**Issue by techjb** [RageAgainstThePixel/OpenAI-DotNet#376]
# Bug Report

## Overview
When using Structured Outputs, only strings fields are marked as required.  According to [OpenAI documentation](https://platform.openai.com/docs/guides/structured-outputs#all-fields-must-be-required) "all fields or function parameters must be specified as required".  
When adding number or boolean fields, they are not marked as required and OpenAI API responds with an error.

## Screenshots
Part of the input schema
![Image](https://github.com/user-attachments/assets/cccbf6b7-dc71-4652-829b-724ecb442b72)

Response from OpenAI:
![Image](https://github.com/user-attachments/assets/86541a4a-f54d-4ac5-8490-0d999950be63)

**Comment by StephenHodgson** [comment]
They recently updated how schemas work on the backend that started breaking existing implementation.

**Comment by techjb** [comment]
Great!
Additionally, I'm missing the Description field. When I add the [Description("text... bla bla...")] attribute to the class, it doesn't appear in the object's description field. I hope this can also be fixed.

**Comment by StephenHodgson** [comment]
> Great! Additionally, I'm missing the Description field. When I add the [Description("text... bla bla...")] attribute to the class, it doesn't appear in the object's description field. I hope this can also be fixed.

it's not an additional attribute, but part of the FunctionAttribute:

https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/b1aba5d1e8d35c698777519deedb4f9642a92dcd/OpenAI-DotNet/Common/FunctionAttribute.cs#L10

```
[Function(description: "blah blah")]
private void Function(){}
```

**Comment by techjb** [comment]
Look at this example in the OpenAI documentation:
https://platform.openai.com/docs/guides/structured-outputs#all-fields-must-be-required

Properties also contains descriptions to give more context.

**Comment by StephenHodgson** [comment]
> Look at this example in the OpenAI documentation: https://platform.openai.com/docs/guides/structured-outputs#all-fields-must-be-required
> 
> Properties also contains descriptions to give more context.

I'm well aware. 

`FunctionPropertyAttribute` also supports descriptions, as well as other things:
https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/b1aba5d1e8d35c698777519deedb4f9642a92dcd/OpenAI-DotNet/Common/FunctionPropertyAttribute.cs#L25

I've already fixed some of this recently just needs to get ported. Recently OpenAI updated their rules on this stuff and broke compatibility. 

I simply disabled `strict` for the tool definitions generated by the built in function attributes, which should fix this issue.

If you provide your own schema definitions, then that is another story.

**Comment by StephenHodgson** [comment]
FWIW if you're using .net 9, then there is a json schema generator that should be compliant: 

https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-9/#json-schema-exporter

**Comment by techjb** [comment]
Thank you for the response. So, is there currently any way to provide attributes with descriptions to obtain a structured outputs?

**Comment by StephenHodgson** [comment]
> Thank you for the response. So, is there currently any way to provide attributes with descriptions to obtain a structured outputs?

see last comment about .net 9 json schema exporter. Likely I'll remove/depricate the custom impl in this library once .net 8 EOL comes around.

**Comment by techjb** [comment]
Finally I was able to add my own schema. I did it using the library Newtonsoft.Json.Schema.


JSchemaGenerator generator = new()
{
    DefaultRequired = Required.AllowNull,
    GenerationProviders =
    {
        new StringEnumGenerationProvider(),
    }
};

JSchema jSChema = generator.Generate(typeof(OpenAIStructuredOutput));
SetAdditionalPropertiesFalse(jSChema); // this method set AllowAdditionalProperties=false to all objects
var schema = jSChema.ToString();
var jsonSchema = new global::OpenAI.JsonSchema("OpenAIStructuredOutput", schema);


var chatRequest = new ChatRequest(
    messages: messages,
    model: MODEL_NAME,
    temperature: TEMPERATURE,
    responseFormat: ChatResponseFormat.JsonSchema,
    jsonSchema: jsonSchema
    );

ChatResponse chatResponse = Task.Run(async () => await OpenAIClient.ChatEndpoint.GetCompletionAsync(chatRequest)).Result;
var structuredOutput = JsonConvert.DeserializeObject<OpenAIStructuredOutput>(chatResponse.FirstChoice);
