### ISSUE TITLE
cannot install the package in my vsto office addin project

### ISSUE THREAD

**Issue by ericliu0408** [RageAgainstThePixel/OpenAI-DotNet#39]
Could you please help to take a look:

Install-Package : Could not install package 'OpenAI-DotNet 5.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does no
t contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package OpenAI-DotNet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:03.0833628

**Comment by StephenHodgson** [comment]
This package only supports .net 6+

You leave the need to upgrade your target framework, or start a new project.
