### ISSUE TITLE
Azure OpenAI - API Key prefix issue

### ISSUE THREAD

**Issue by knavet** [RageAgainstThePixel/OpenAI-DotNet#49]
# Bug Report
Library expects API Key to starts with **"sk-"**. This works for OpenAI keys, but Azure's OpenAI api keys does not start with this prefix.

## Overview

OPENAI Api Key prefix = "sk-" - correct
Azure OpenAI Api Key prefix = "" - Azure has no prefix.

This resulted in the wrong key being passed to Azure OpenAI.

**Comment by StephenHodgson** [comment]
Thanks for the report. I'll issue a fix shortly.
