### ISSUE TITLE
Setting http request timeout

### ISSUE THREAD

**Issue by grishin** [RageAgainstThePixel/OpenAI-DotNet#53]
# Feature Request

## Is your feature request related to a problem? Please describe.
I need to increase default timeout for requests to OpenAI api.

## Describe the solution you'd like
Make internal constructor with HttpClient parameter public.

## Describe alternatives you've considered
Reflection.

**Comment by StephenHodgson** [comment]
Sure I think we can make the constructor public.

**Comment by StephenHodgson** [comment]
Although I'm curious what has been the default time out for you that's been working?

**Comment by grishin** [comment]
Thank you very much! I upgraded to version 6.4.1 and everything works out of the box without reflection hacks. 

I use Timeout = TimeSpan.FromSeconds(300) , their api works seriously unstable in peak times. Also I'm thinking about much shorter timeout and http request retries with Polly.

**Comment by StephenHodgson** [comment]
> It's also useful for letting the HttpClientFactory from DI extensions handle the creation of HttpClients.

Literally how the tests work 😅

**Comment by StephenHodgson** [comment]
The constructor is no longer internal . This shouldn't be an issue any longer.

**Comment by johnkors** [comment]
Sure. Talking past tense 👍
