### ISSUE TITLE
Remove requirement for Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by grishin** [RageAgainstThePixel/OpenAI-DotNet#54]
# Feature Request

## Is your feature request related to a problem? Please describe.
Version 5 of OpenAI-DotNet was running without problems on dotnet/runtime docker base image (the one with minimal dotnet and no asp.net libraries). Version 6.3.1 requires running on dotnet/aspnet base image.  https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/main/OpenAI-DotNet/OpenAI-DotNet.csproj#L102 . Now it is impossible to use this library in console apps (e.g. telegram bot).

## Describe the solution you'd like
Remove requirements for asp.net.

## Describe alternatives you've considered
Run console apps on asp.net docker images (much heavier).

**Comment by StephenHodgson** [comment]
What's interesting is I did test this to see if it was going to be a problem. In my initial tests it didn't look like the console apps how to dependency.

I'm also open to other suggestions for solutions. 

I've also considered adding a compiler symbol, but I couldn't figure out how to make it dependent on if the asp.net libraries were referenced.

**Comment by StephenHodgson** [comment]
Good news! Nuget got back to me and released the block. I'll likely publish as a separate package after all.

**Comment by StephenHodgson** [comment]
@grishin btw did my latest attempt to fix actually resolve this issue for you?

**Comment by grishin** [comment]
Everything works now on runtime docker image, thanks a ton!
