### ISSUE TITLE
Question regarding conversations

### ISSUE THREAD

**Issue by DrPoncho** [RageAgainstThePixel/OpenAI-DotNet#56]
Hi there,

For starters - thanks for your great work! Adding support for a proxy is going above and beyond, it's really appreciated :)

I have a question though, I can't seem to find how to hold actual conversations. In the previous [forked library](https://github.com/OkGoDoIt/OpenAI-API-dotnet), you create a conversation, and then add user input etc:

```csharp
var chat = api.Chat.CreateConversation();
chat.AppendUserInput("Is this an animal? Cat");
```

In your version, I created a `ChatRequest` with a `List<ChatPrompt>` bound to it. I then created an extension method to easily add `ChatPrompt` objects to that list, with either system, assistant or user as its role. 

At first that works fine. I add a system message explaining to the assistant what his role is, and it introduces itself.

However, after adding a new `ChatPrompt` with a user-role question and then running `ChatEndpoint.GetCompletionAsync(_chatRequest)` again, the conversation just starts over and the assistant introduces itself again.

How can I keep the conversation going, without having to create a new `ChatRequest` every time? Or is that the way to go?

**Comment by StephenHodgson** [comment]
I purposefully left this library sparse on purpose and only implementing the API. It's up to you to implement the chat functionality how you wish.

Yes you need to pass the entire conversation did the API for each request. The last library used probably did the same for you under the hood, but I wanted to give developers the flexibility to implement this however they wish.

**Comment by ADefWebserver** [comment]
For an example see: https://github.com/SyncfusionSuccinctlyE-Books/OpenAI-Succinctly/blob/main/Pages/ChatGPT.razor#L160

```
            // Create a new OpenAIClient object
            // with the provided API key and organization
            var api = new OpenAIClient(new OpenAIAuthentication(ApiKey, Organization));

            // Create a new list of ChatPrompt objects and initialize it with the
            // system's introductory message
            var chatPrompts = new List<ChatPrompt>();
            chatPrompts.Add(new ChatPrompt("system", "You are helpful Assistant"));

            // Add all existing messages to chatPrompts
            foreach (var item in messages)
            {
                chatPrompts.Add(new ChatPrompt(item.Role, item.Prompt));
            }

            // Add the new message to chatPrompts
            chatPrompts.Add(new ChatPrompt("user", prompt));

            // Call ChatGPT
            // Create a new ChatRequest object with the chat prompts and pass
            // it to the API's GetCompletionAsync method
            var chatRequest = new ChatRequest(chatPrompts);
            var result = await api.ChatEndpoint.GetCompletionAsync(chatRequest);

            // Create a new Message object with the user's prompt and other
            // details and add it to the messages list
            messages.Add(new Message
                {
                    Prompt = prompt,
                    Role = "user",
                    Tokens = result.Usage.PromptTokens
                });

            // Create a new Message object with the response and other details
            // and add it to the messages list
            messages.Add(new Message
                {
                    Prompt = result.FirstChoice.Message,
                    Role = "assistant",
                    Tokens = result.Usage.CompletionTokens
                });

            // Update the total number of tokens used by the API
            TotalTokens = TotalTokens + result.Usage.TotalTokens;
```

**Comment by DrPoncho** [comment]
Perfect, thanks @ADefWebserver ❤️
