### ISSUE TITLE
Unable to use fine tuned model

### ISSUE THREAD

**Issue by matwurks** [RageAgainstThePixel/OpenAI-DotNet#58]
It appears that you should be able to pass in a model ID to openAI API to use a specified fine tuned model: 

https://platform.openai.com/docs/api-reference/completions

however: 
`      this.Model = (string) (model ?? OpenAI.Models.Model.GPT3_5_Turbo);
      if (!this.Model.Contains("turbo") && !this.Model.Contains("gpt-4"))
        throw new ArgumentException(this.Model + " is not supported", nameof (model));`

seems like you must have it named in a particular way. further, 

in the createfinetunejobrequest class: 

'      this.Model = model ?? "curie";'

I believe model should not be defaulted to null. It should be a required parameter - to name the model for the fine tune request.

**Comment by ADefWebserver** [comment]
This works for me: https://github.com/SyncfusionSuccinctlyE-Books/OpenAI-Succinctly/blob/main/Pages/FineTuningExample.razor

```
           var api = new OpenAIClient(new OpenAIAuthentication(ApiKey, Organization));

            var objModel = await api.ModelsEndpoint.GetModelDetailsAsync(CompletionModel);

            List<string> StopSequence = new List<string>() { "->", "." };

            var result = await api.CompletionsEndpoint.CreateCompletionAsync(
                CompletionPrompt, maxTokens: 100, echo: false,
                temperature: 0.1, stopSequences: StopSequence, model: objModel);

            foreach (var completion in result.Completions)
            {
                CompletionResponse += completion.Text;
            }
```

**Comment by StephenHodgson** [comment]
> however:
      this.Model = (string) (model ?? OpenAI.Models.Model.GPT3_5_Turbo); if (!this.Model.Contains("turbo") && !this.Model.Contains("gpt-4")) throw new ArgumentException(this.Model + " is not supported", nameof (model));
>
> seems like you must have it named in a particular way.

I don't believe you can use fine-tune models for chat anyway. The example you provided above is from the chat end point.

**Comment by StephenHodgson** [comment]
In either case, I'll add a unit test to make sure that fine tune models can be used for the regular completions endpoint just a verify that this is working as expected

**Comment by StephenHodgson** [comment]
Confirmed this is working as expected.

**Comment by matwurks** [comment]
> > however:
> > this.Model = (string) (model ?? OpenAI.Models.Model.GPT3_5_Turbo); if (!this.Model.Contains("turbo") && !this.Model.Contains("gpt-4")) throw new ArgumentException(this.Model + " is not supported", nameof (model));
> > seems like you must have it named in a particular way.
> 
> [I don't believe you can use fine-tuned models for chat anyway]

This is what the problem was. I missed this. thank you for the help!
