### ISSUE TITLE
Project structure and easy(ier) to edit files

### ISSUE THREAD

**Issue by Baklap4** [RageAgainstThePixel/OpenAI-DotNet#61]
# Feature Request

Clean up of the project structure

## Is your feature request related to a problem? Please describe.
Not all files are available within the IDE (VS2022) which makes them hard(er) to edit.

## Describe the solution you'd like

1. Add solution directories to contain these files.
2. Split up Tests and Source
3. ~~Add Examples directory to contain example applications.~~ Not needed as of yet
4. Add editorconfig

**Comment by StephenHodgson** [comment]
I appreciate the suggestions, but I like how the project is structured at the moment.

I don't mind adding the additional files to the solution items if it makes it easier to edit.
