### ISSUE TITLE
Add Optional Mask parameter overload for image edits

### ISSUE THREAD

**Issue by Offline-R503B** [RageAgainstThePixel/OpenAI-DotNet#64]
Didn't want to make this to complicated : 

The edit image function has the mask as optional as per the API reference, but with this repo it's required, if you can be so kind to set it to optional 👍  

Or if I am completely wrong and I need to use it in some other form feel free to explain!

quick edit, Love the rest of the repo , and thanks for making the nuget a big more visible!

**Comment by StephenHodgson** [comment]
Did you try just passing null?
