### ISSUE TITLE
EditEndpoint no longer works

### ISSUE THREAD

**Issue by Dmitrys91** [RageAgainstThePixel/OpenAI-DotNet#68]
# Bug Report

## Overview

Using the EditEndpoint, it does not work. Davinci 3 removed. And i can't add my own because you added some weird validation (-edit- ???)

**Comment by StephenHodgson** [comment]
This is a bug with open AI, not the library.

I noticed it too last week well I was running some of my unit tests, but their website still lists the models as valid.

**Comment by StephenHodgson** [comment]
Also please go back and fill out the issue report. 

I need to know specifically which endpoints you're speaking about

**Comment by ADefWebserver** [comment]
See: [The model: `text-davinci-edit-001` does not exist](https://community.openai.com/t/the-model-text-davinci-edit-001-does-not-exist/116144)

**Comment by StephenHodgson** [comment]
If it is the edits endpoint, then you're not able to use your own custom models anyway.

**Comment by Dmitrys91** [comment]
> This is a bug with open AI, not the library.
> 
> I noticed it too last week well I was running some of my unit tests, but their website still lists the models as valid.

okay, but why i can not create my own EditRequest with the custom Model? PLease see the constructor

**Comment by StephenHodgson** [comment]
It's not up to me, if you try to use it with a custom model it will reject it anyway. There's no way to train a custom model for the edit end point.

**Comment by StephenHodgson** [comment]
Since this is not a problem with the library itself I'm going to go ahead and close this.

**Comment by StephenHodgson** [comment]
See #70

**Comment by ADefWebserver** [comment]
Are you sure this is correct? The OpenAI team member said:

Double checking with the team on this, the models I am aware of that were removed are:

code-cushman:001
code-cushman:002
code-davinci:001
code-davinci:002

**Comment by StephenHodgson** [comment]
Seems to be the case.

**Comment by ADefWebserver** [comment]
I'm actually working on a book and I was on the "Edits" chapter and discovered that suddenly it wasn't working. I was about to just delete the chapter but decided to wait for a response from OpenAI. Based on the last response I decided to keep the chapter then saw that you marked it obsolete 😬 This is a problem because I-am-using-your-library-in-the-book 😬 So... can we give OpenAI a few more days? Thanks!

**Comment by StephenHodgson** [comment]
No problem I didn't completely remove it for this reason.

**Comment by ADefWebserver** [comment]
It's back! 👍🏾 
https://community.openai.com/t/the-model-text-davinci-edit-001-does-not-exist/116144/28?u=adefwebserver
![image](https://user-images.githubusercontent.com/1857799/228008481-eb54ac97-bb20-4913-afc0-8583bebb498d.png)
