### ISSUE TITLE
Renovations Needed

### ISSUE THREAD

**Issue by kinetiq** [RageAgainstThePixel/OpenAI-DotNet#7]
Thanks for keeping this library going. I ran into a few issues:
 - The Engine endpoint that you use for completions appears to be marked obsolete in the docs. There's a new endpoint for that now, with similar semantics. 
 - I'm not sure you are using the newest version of davinci, or that it's possible to use it the way this is set up. I may be missing something.
 - When doing a ~2000 token request that contained some text that had to be escaped by your API before the JSON could be transmitted, I continuously received responses very different from what I got through playground. Something is wrong there.

Not sure if that's the engine, the endpoint, or a quirk of escaping special characters. I spent hours trying to get this to work and then discovered this repo: https://github.com/betalgo/openai which uses newer endpoints and with that one, the problems went away. Your syntax is a little more to my liking and your API implementation is more robust. But I've switched over for now. Just wanted to say thanks for the hard work and to share my experience.

**Comment by StephenHodgson** [comment]
Thanks for the feedback. I'll look into the new API changes

**Comment by StephenHodgson** [comment]
I've updated the end points in the unity version of this library but not this one yet.

**Comment by StephenHodgson** [comment]
Since the old APIs have been deprecated and shut down I definitely need to get on to modernizing this library
