### ISSUE TITLE
Add Dashboard/Usage API

### ISSUE THREAD

**Issue by Muchaszewski** [RageAgainstThePixel/OpenAI-DotNet#78]
# Feature Request

## Is your feature request related to a problem? Please describe.

OpenAI Dashboard uses the same endpoint that prompting and can be easily used to display all information about current usage and billing. This API seems to not be documented Eg:
```
https://api.openai.com/dashboard/billing/usage?end_date=2023-05-01&start_date=2023-04-01
```
![image](https://user-images.githubusercontent.com/5092066/230607234-6d94899f-a730-4060-b4d5-f52761601dd9.png)

/dashboard requires different authentication
/v1 but undocumented method work with API keys

## Describe the solution you'd like

Information about billing and other dashboard information could be fetched using the same package

## Describe alternatives you've considered

PR or writing extending the OpenAI-DotNet functionality to reuse auth keys

## Additional context

Other endpoints that could prove useful
```
https://api.openai.com/v1/usage?date=2023-04-07
https://api.openai.com/v1/organizations/org-XXX/users

https://api.openai.com/dashboard/billing/usage?end_date=2023-05-01&start_date=2023-04-01
https://api.openai.com/dashboard/billing/credit_grants
https://api.openai.com/dashboard/billing/subscription
https://api.openai.com/dashboard/organizations/org-XXX/features
https://api.openai.com/dashboard/user/api_keys
```

**Comment by StephenHodgson** [comment]
Is this endpoint undocumented?

**Comment by ADefWebserver** [comment]
See: https://community.openai.com/t/how-to-track-individual-usage/15935/16

**Comment by StephenHodgson** [comment]
I believe `/dashboard` is only if you're logged into the website with their OAuth provider.

**Comment by StephenHodgson** [comment]
I'm going to close this as I would only like to support officially recognized endpoints.
