### ISSUE TITLE
.NET version?

### ISSUE THREAD

**Issue by matt1966** [RageAgainstThePixel/OpenAI-DotNet#8]
`Could not install package 'OpenAI-DotNet 3.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`	

I'm getting the following error. Does this mean it does not work on  => 4.7.2?

**Comment by StephenHodgson** [comment]
You may need to update to using the more modern net5+

**Comment by StephenHodgson** [comment]
I'll update the documentation when I release a new version.
