### ISSUE TITLE
Bug when GetAuthFromFile

### ISSUE THREAD

**Issue by AwesomeYuer** [RageAgainstThePixel/OpenAI-DotNet#82]
# Bug Report

https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/b7117911e1c99c94ff21709a74c794c05149787b/OpenAI-DotNet/OpenAIAuthentication.cs#L175
It should as below

```csharp
for (var i = 0; i < parts.Length - 1; i++)
```

## To Reproduce
unittest for 
```
 [Test]
 public void Test_02_GetAuthFromFile()
```

## Expected behavior
 get config from `.openai`

## Screenshots

![Untitled](https://user-images.githubusercontent.com/1026479/231057973-19669938-a052-4722-8f9b-3b17ed6af33a.png)

**Comment by StephenHodgson** [comment]
can you please give me an example of the format for your `.openai` file with sensitive info stripped out please?

**Comment by AwesomeYuer** [comment]
https://github.com/AwesomeYuer/OpenAI.Embeddings.pgvector.NET/blob/main/ConsoleApp1/.openai.example

> can you please give me an example of the format for your `.openai` file with sensitive info stripped out please?

https://github.com/AwesomeYuer/OpenAI.Embeddings.pgvector.NET/blob/main/ConsoleApp1/.openai.example

**Comment by StephenHodgson** [comment]
I've fixed it but I do want to emphasize that the env file is deprecated for the new json format.
