### ISSUE TITLE
Enable Github Discussions 

### ISSUE THREAD

**Issue by ADefWebserver** [RageAgainstThePixel/OpenAI-DotNet#84]
# Feature Request

## Is your feature request related to a problem? Please describe.
Allow users to discuss issues without raising a Github "Issue"

## Describe the solution you'd like
Enable Github Discussions

## Describe alternatives you've considered
N/A

**Comment by StephenHodgson** [comment]
https://discord.gg/xQgMW9ufN4

**Comment by ADefWebserver** [comment]
Can we post that on the home page?

**Comment by StephenHodgson** [comment]
I believe the link is there

**Comment by StephenHodgson** [comment]
![image](https://user-images.githubusercontent.com/13334553/231585718-f22c700a-943d-49ce-8d8f-728939965785.png)

**Comment by StephenHodgson** [comment]
But bc this repo is mirrored with the Unity one I don't feel like having multiple places to look for this kinda thing

**Comment by ADefWebserver** [comment]
Understood. 

The only advantage was that we could have a place to share code samples (that would be discoverable by search engines) and answer questions from newbies. The point would be that *you* would not have to answer and close every "issue" (like you have to do now).

Since I have a book coming out that uses this library I am *very* invested in its growth and survival :)
