### ISSUE TITLE
How do i send over a 16k token prompt ?

### ISSUE THREAD

**Issue by sir-stefan-ciobanu** [RageAgainstThePixel/OpenAI-DotNet#86]
Hi, 
First off, nice library and thank you for sharing 👍 .
I got a question regarding "huge" prompts. Using :
```
var api = new OpenAIClient();
var chatPrompts = new List<ChatPrompt>
{
    new ChatPrompt("system", "You are a helpful assistant."),
    new ChatPrompt("user", "Who won the world series in 2020?"),
    new ChatPrompt("assistant", "The Los Angeles Dodgers won the World Series in 2020."),
    new ChatPrompt("user", "Where was it played?"),
};
var chatRequest = new ChatRequest(chatPrompts, Model.GPT3_5_Turbo);

await api.ChatEndpoint.StreamCompletionAsync(chatRequest, result =>
{
    Console.WriteLine(result.FirstChoice);
});
```

and adding chunks of 4k tokens as ChatPrompts then sending the chat prompts via `var chatRequest = new ChatRequest(chatPrompts, Model.GPT3_5_Turbo);` seems to result in a 4096 limit complaint as a response. How would i be able to send such kind of prompts then ask a question ? Thank you !

**Comment by StephenHodgson** [comment]
I believe that is only supported by the `gpt-4-32k` model. You need special access for it. If you did have access you'd just specify it in the model parameter:

```csharp
var chatRequest = new ChatRequest(chatPrompts, new Model("gpt-4-32k"));
```
