### ISSUE TITLE
Blazor WASM Hosted - Request Fails from Razor Page

### ISSUE THREAD

**Issue by GraemeWellington** [RageAgainstThePixel/OpenAI-DotNet#89]
# Bug Report

## Overview
I am testing OpenAI-DotNet in Blazor WASM Hosted [Client/Server].
The sample code below work in Blazor Server.
However in Blazor WASM Hosted the chat request fails with response 'The given header was not found.'
I can get a list of models using sample code provided:
```csharp
protected override async Task OnInitializedAsync()
    {
string ApiKey = "<Your API-KEY>";
var api = new OpenAIClient(new OpenAIAuthentication(ApiKey, Organization));
        var models = await api.ModelsEndpoint.GetModelsAsync();
        foreach (var model in models)
        {
            Console.WriteLine("OpenAIModels: " + model.ToString());
        }
}
```
However a simple request fails with the 'response 'The given header was not found.'
```csharp
protected override async Task OnInitializedAsync()
    {
string ApiKey = "<Your API-KEY>";
var api = new OpenAIClient(new OpenAIAuthentication(ApiKey, Organization));
await api.CompletionsEndpoint.StreamCompletionAsync(result =>
       {
          foreach (var choice in result.Completions)
               {
               Console.WriteLine(choice);
       }
       }, "My name is Roger and I am a principal software engineer at Salesforce.  This is my resume:", maxTokens: 200, temperature: 0.5, presencePenalty: 0.1, frequencyPenalty: 0.1, model: OpenAI.Models.Model.Davinci);
}
}
```

## To Reproduce
1. Create Blazor WASM Hosted solution
2. Add Nuget OpenAI-DotNet to Client
3. Add razor page and add the code above [Note an ApiKey is required]

## Expected behavior
Response: I am an experienced Software Engineer with 5+ years of experience...

## Additional context
crit: 
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The given header was not found.
System.InvalidOperationException: The given header was not found.
   at System.Net.Http.Headers.HttpHeaders.GetValues(HeaderDescriptor descriptor)
   at System.Net.Http.Headers.HttpHeaders.GetValues(String name)
   at OpenAI.ResponseExtensions.SetResponseData(BaseResponse response, HttpResponseHeaders headers)
   at OpenAI.ResponseExtensions.DeserializeResponse[CompletionResult](HttpResponseMessage response, String json, JsonSerializerOptions settings)
   at OpenAI.Completions.CompletionsEndpoint.CreateCompletionAsync(CompletionRequest completionRequest, CancellationToken cancellationToken)
   at OpenAI.Completions.CompletionsEndpoint.CreateCompletionAsync(String prompt, IEnumerable`1 prompts, String suffix, Nullable`1 maxTokens, Nullable`1 temperature, Nullable`1 topP, Nullable`1 numOutputs, Nullable`1 presencePenalty, Nullable`1 frequencyPenalty, Nullable`1 logProbabilities, Nullable`1 echo, IEnumerable`1 stopSequences, Model model, CancellationToken cancellationToken)
   at BlazorFileSystem.Client.Pages.OpenAI_5.GenerateResponse() in C:\_PTBSX-Dev\_Blazor\BTE\BlazorFileSystem\BlazorFileSystem\Client\Pages\OpenAI-5.razor:line 42
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by ADefWebserver** [comment]
If you make the API call to OpenAI from Blazor client your API key would leak. In a Blazor server hosted application you would make the call from the hosted server part. That is working fine. See: https://github.com/SyncfusionSuccinctlyE-Books/OpenAI-Succinctly

**Comment by GraemeWellington** [comment]
Thanks Michael Yes I get it now!
So I sat down with Chat GPT and worked out a coarse (not pretty) Blazor WASM Hosted solution with Client Razor Page / Server Controller (which gets ApiKey from appsettings,json in Server project [using Nuget Package: OpenAI-DotNet].
Thanks for your help - I love your work!

Client.Data.MessageSave.cs
`using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using OpenAI.Chat;

namespace BlazorWASMHosted7.Shared.Data
{
    public class MessageSave
    {
        public string? Prompt { get; set; }
        public Role Role { get; set; }
        public int Tokens { get; set; }
    }
}`
Client.Pages.OpenAIDotNetChat.razor
`@page "/OpenAIDotNetChat"
@using BlazorWASMHosted7.Shared.Data
@inject HttpClient HttpClient
@inject IJSRuntime _jsRuntime

<h3>OpenAI-DotNet Chat [Blazor WASM Hosted]</h3>
<p>Client OpenAIDotNetChat.razor makes http call to Server Controller: OpenAIDotNetChatController.cs</p>

<hr />
<p>This page uses Nuget: OpenAI-DotNet Version 6.7.2 [Stephen Hodgson]</p>
<hr />

<style>
    textarea {
        border: 1px dashed #888;
        border-radius: 5px;
        width: 80%;
        overflow: auto;
        background: #f7f7f7
    }

    /* improved CSS for speech bubbles */

    .assistant, .user {
        position: relative;
        font-family: arial;
        font-size: 1.1em;
        border-radius: 10px;
        padding: 20px;
        margin-bottom: 20px;
    }

        .assistant:after, .user:after {
            content: '';
            border: 20px solid transparent;
            position: absolute;
            margin-top: -30px;
        }

    .user {
        background: #03a9f4;
        color: #fff;
        margin-left: 20%;
        margin-right: 100px;
        top: 30%;
        text-align: right;
    }

    .assistant {
        background: #4CAF50;
        color: #fff;
        margin-left: 100px;
        margin-right: 20%;
    }

    .user:after {
        border-left-color: #03a9f4;
        border-right: 0;
        right: -20px;
    }

    .assistant:after {
        border-right-color: #4CAF50;
        border-left: 0;
        left: -20px;
    }

    .msg {
        font-size: medium;
    }
</style>

<p style="font-size:small"><b>Total Tokens:</b> @TotalTokens</p>
<div id="chatcontainer" style="height:550px; width:80%; overflow: scroll;">
    @foreach (var item in Messages)
    {
        <div>
            @if (item.Role == OpenAI.Chat.Role.User)
            {
                <div style="float: right; margin-right: 20px; margin-top: 10px">
                    <b>Human</b>
                </div>
                <div class="@item.Role.ToString().ToLower()">
                    <div class="msg">
                        @item.Prompt
                        <br /><br />
                        <div style="font-size:xx-small;">
                            <i><b>(@item.Tokens)</b> Tokens</i>
                        </div>
                    </div>
                </div>
            }
            else
            {
                <div style="float: left; margin-left: 20px; margin-top: 10px">
                    <b>ChatGPT&nbsp;&nbsp;</b>
                </div>
                <div class="@item.Role.ToString().ToLower()">
                    <div class="msg">
                        @if (item.Prompt != null)
                        {
                            @((MarkupString)item.Prompt)
                        }
                        <br /><br />
                        <div style="font-size:xx-small;">
                            <i><b>(@item.Tokens)</b> Tokens</i>
                        </div>
                    </div>
                </div>
            }
        </div>
    }
</div>
@if (!Processing)
{
    <textarea rows="3" cols="60" @bind="prompt" />
    <br />
    <button class="btn btn-primary"
        @onclick="CallChatGPT">
        Call ChatGPT
    </button>
    <span>&nbsp;</span>
    <button class="btn btn-info"
        @onclick="RestartChatGPT">
        Restart
    </button>
}
else
{
    <br>
    <h4>Processing...</h4>
}
<br /><p style="color:red">@ErrorMessage</p>

@code {

    List<MessageSave> Messages = new List<MessageSave>();
    string prompt = "Write a 10 word description of OpenAI ChatGPT";
    string ErrorMessage = "";
    bool Processing = false;
    int totalTokens = 0;
    int TotalTokens = 0;

    private async Task CallChatGPT()
    {
        var response = await HttpClient.PostAsJsonAsync("api/OpenAIDotNetChat/search", prompt);
        if (response.IsSuccessStatusCode)
        {
            var messages = await response.Content.ReadFromJsonAsync<List<MessageSave>>();
            Messages.AddRange(messages);
            prompt = "";

            // Update the total number of tokens used by the API
            foreach (var message in messages)
            {
                totalTokens += message.Tokens;
            }
            TotalTokens = totalTokens;
        }
    }
    void RestartChatGPT()
    {
        prompt = "Write a 10 word description of OpenAI ChatGPT";
        Messages = new List<MessageSave>();
        totalTokens = 0;
        TotalTokens = 0;
        ErrorMessage = "";
        StateHasChanged();
    }
}
`
Server.Controllers.OpenAIDotNetChatController.cs
`using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.DataProtection.KeyManagement;
using Microsoft.Extensions.Configuration;
using BlazorWASMHosted7.Shared.Data;
using OpenAI;
using OpenAI.Chat;
using OpenAI.Models;
using OpenAI_API.Chat;

namespace BlazorWASMHosted7.Server.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class OpenAIDotNetChatController : Controller
    {
        private readonly IConfiguration _configuration;
        public OpenAIDotNetChatController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
      
        [HttpPost ("search")]
        public async Task<ActionResult<List<MessageSave>>> CallChatGPT([FromBody] string prompt)
        {
            var organization = _configuration["OpenAIServiceOptions:Organization"] ?? "";
            var apiKey = _configuration["OpenAIServiceOptions:ApiKey"] ?? "";

            var messages = new List<MessageSave>();

            try
            {
                // Create a new OpenAIClient object with the provided API key and organization
                var _api = new OpenAIClient(new OpenAIAuthentication(apiKey, organization));

                // Create a new list of chatMessages objects and initialize it with the system's introductory message
                var chatMessages = new List<Message>();
                chatMessages.Add(new Message(Role.System, "You are helpful Assistant"));

                // Add all existing messages to chatMessages
                foreach (var item in messages)
                {
                    chatMessages.Add(new Message(item.Role, item.Prompt));
                }

                // Add the new message to chatMessages
                chatMessages.Add(new Message(Role.User, prompt));

                // Call ChatGPT
                // Create a new ChatRequest object with the chat prompts and pass it to the API's GetCompletionAsync method
                var chatRequest = new OpenAI.Chat.ChatRequest(chatMessages);
                var result = await _api.ChatEndpoint.GetCompletionAsync(chatRequest);

                // Create a new MessageSave object with the user's prompt and other details and add it to the messages list
                messages.Add(new MessageSave
                {
                    Prompt = prompt,
                    Role = Role.User,
                    Tokens = result.Usage.PromptTokens
                });

                // Create a new MessageSave object with the response and other details and add it to the messages list
                messages.Add(new MessageSave
                {
                    Prompt = result.FirstChoice.Message,
                    Role = Role.Assistant,
                    Tokens = result.Usage.CompletionTokens
                });

                return Ok(messages);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
                         
    }
}`

**Comment by ADefWebserver** [comment]
@GraemeWellington than you for posting a complete solution because that will help others. The only thing I would add, is that `OpenAIDotNetChatController `may need to have `[Authentication]` to protect it from being accessed it by hackers. While your **OpenAI** keys are safe (good!) the controller still allows anyone to make a call to **OpenAI** outside of your program.

**Comment by StephenHodgson** [comment]
@ADefWebserver we need to get your links setup in the docs once you publish

**Comment by ADefWebserver** [comment]
@StephenHodgson You can post the GitHub link now. The book may be delayed in publishing.
