### ISSUE TITLE
Use IHttpClientFactory or pooled connections

### ISSUE THREAD

**Issue by bonsall** [RageAgainstThePixel/OpenAI-DotNet#92]
# Feature Request

## Problem
`HttpClient` has known issues with socket exhaustion and dns change detection. These issues (as well as solutions) are described in this article from Microsoft [https://learn.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)

## Solution
Update the code to use the `IHttpClientFactory` to create short lived `HttpClient`s that are created/destroyed when making requests. Or use a single `HttpClient` instance that has a `PooledConnectionLifetime` set to a timespan other than `Timeout.Inifinite`. Since this project is already using a singleton `HttpClient` instance it looks like the best (easiest) solution is the latter, in which the `PooledConnectionLifetime` property is set.

**Comment by bonsall** [comment]
I could probably knock this out over the weekend. Are there any guidelines for committing to this repo?

**Comment by StephenHodgson** [comment]
Make a fork, commit to your branch in your fork, open a pull request on main repo.
