### ISSUE TITLE
Usage is always null when done streaming chat

### ISSUE THREAD

**Issue by alejandro5042** [RageAgainstThePixel/OpenAI-DotNet#94]
# Bug Report

## Overview
Usage is always null when streaming, even if the stream is complete.

## To Reproduce
Attempt a stream against the chat models via `StreamCompletionEnumerableAsync`.

## Expected behavior
At the end, I would expect the last result to contain `Usage`, but it doesn't (at least on my PC).

## Screenshots
![image](https://user-images.githubusercontent.com/3143819/236404443-543eaff4-dd3b-4a54-895d-7a965ba363cb.png)

## Additional context
The non-streaming way does return non-null `Usage`.

**Comment by StephenHodgson** [comment]
Sorry I misread your issue. 

I will see what I can do to check to make sure the usage reflects properly in the event data, and if it does, set that in the final message result.

**Comment by alejandro5042** [comment]
Thanks for looking into this, I appreciate the helpful notes!
